//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "TSThread.h"

NS_ASSUME_NONNULL_BEGIN

@class DTConversationSharingConfigurationNotifyEntity;

@interface TSContactThread : TSThread

//ask friend
@property (nonatomic, assign) BOOL receivedFriendReq;
@property (nonatomic, assign) NSInteger friendContactVersion;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                    archivalDate:(nullable NSDate *)archivalDate
              conversationEntity:(nullable DTConversationEntity *)conversationEntity
                    creationDate:(NSDate *)creationDate
             draftQuoteMessageId:(nullable NSString *)draftQuoteMessageId
                expiresInSeconds:(unsigned long long)expiresInSeconds
               hasEverHadMessage:(BOOL)hasEverHadMessage
                      isArchived:(BOOL)isArchived
                 lastMessageDate:(nullable NSDate *)lastMessageDate
                      lastestMsg:(nullable TSMessage *)lastestMsg
                 mentionedAllMsg:(nullable DTMentionedMsgInfo *)mentionedAllMsg
                  mentionedMeMsg:(nullable DTMentionedMsgInfo *)mentionedMeMsg
                   mentionsDraft:(nullable NSArray<DTMention *> *)mentionsDraft
              messageClearAnchor:(unsigned long long)messageClearAnchor
                    messageDraft:(nullable NSString *)messageDraft
                  mutedUntilDate:(nullable NSDate *)mutedUntilDate
                 plainTextEnable:(BOOL)plainTextEnable
              readPositionEntity:(nullable DTReadPositionEntity *)readPositionEntity
         removedFromConversation:(BOOL)removedFromConversation
                 shouldBeVisible:(BOOL)shouldBeVisible
                stickCallingDate:(nullable NSDate *)stickCallingDate
                       stickDate:(nullable NSDate *)stickDate
                    threadConfig:(nullable DTThreadConfigEntity *)threadConfig
            translateSettingType:(nullable NSNumber *)translateSettingType
                      unreadFlag:(unsigned int)unreadFlag
              unreadMessageCount:(NSUInteger)unreadMessageCount
                     unreadState:(NSUInteger)unreadState
            unreadTimeStimeStamp:(unsigned long long)unreadTimeStimeStamp
            friendContactVersion:(NSInteger)friendContactVersion
              hasDismissedOffers:(BOOL)hasDismissedOffers
               receivedFriendReq:(BOOL)receivedFriendReq
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:archivalDate:conversationEntity:creationDate:draftQuoteMessageId:expiresInSeconds:hasEverHadMessage:isArchived:lastMessageDate:lastestMsg:mentionedAllMsg:mentionedMeMsg:mentionsDraft:messageClearAnchor:messageDraft:mutedUntilDate:plainTextEnable:readPositionEntity:removedFromConversation:shouldBeVisible:stickCallingDate:stickDate:threadConfig:translateSettingType:unreadFlag:unreadMessageCount:unreadState:unreadTimeStimeStamp:friendContactVersion:hasDismissedOffers:receivedFriendReq:));

// clang-format on

// --- CODE GENERATION MARKER

@property (nonatomic) BOOL hasDismissedOffers;

- (instancetype)initWithContactId:(NSString *)contactId;

+ (instancetype)getOrCreateThreadWithContactId:(NSString *)contactId NS_SWIFT_NAME(getOrCreateThread(contactId:));

+ (instancetype)getOrCreateThreadWithContactId:(NSString *)contactId
                                   transaction:(SDSAnyWriteTransaction *)transaction;

+ (instancetype)getOrCreateThreadWithContactId:(NSString *)contactId
                                   transaction:(SDSAnyWriteTransaction *)transaction
                                         relay:(nullable NSString *)relay;

// Unlike getOrCreateThreadWithContactId, this will _NOT_ create a thread if one does not already exist.
+ (nullable instancetype)getThreadWithContactId:(NSString *)contactId
                                    transaction:(SDSAnyReadTransaction *)transaction NS_SWIFT_NAME(getThread(contactId:transaction:));

- (NSString *)contactIdentifier;

- (NSString *)contactIdentifier_callNumber;

+ (NSString *)contactIdFromThreadId:(NSString *)threadId;

+ (NSString *)threadIdFromContactId:(NSString *)contactId;

+ (void)updateWithRecipientId:(NSString *)recipientId
         friendContactVersion:(NSInteger)friendContactVersion
            receivedFriendReq:(BOOL)receivedFriendReq
       updateAtTheSameVersion:(BOOL)updateAtTheSameVersion
                  transaction:(SDSAnyWriteTransaction *)transaction;

- (NSString *)generateConversationId;

@end

NS_ASSUME_NONNULL_END
