//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "TSGroupModel.h"
#import "TSThread.h"

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, TSGroupTransitionStatus) {
    TSGroupTransitionStatusOld = 0,
    TSGroupTransitionStatusOldToNew = 1,
    TSGroupTransitionStatusNew = 2,
    TSGroupTransitionStatusUnknown = 3
};

@class TSAttachmentStream;
@class SDSAnyWriteTransaction;

extern NSString *const TSGroupThreadAvatarChangedNotification;
extern NSString *const TSGroupThread_NotificationKey_UniqueId;

@interface TSGroupThread : TSThread

@property (nonatomic, strong) TSGroupModel *groupModel;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                    archivalDate:(nullable NSDate *)archivalDate
              conversationEntity:(nullable DTConversationEntity *)conversationEntity
                    creationDate:(NSDate *)creationDate
             draftQuoteMessageId:(nullable NSString *)draftQuoteMessageId
                expiresInSeconds:(unsigned long long)expiresInSeconds
               hasEverHadMessage:(BOOL)hasEverHadMessage
                      isArchived:(BOOL)isArchived
                 lastMessageDate:(nullable NSDate *)lastMessageDate
                      lastestMsg:(nullable TSMessage *)lastestMsg
                 mentionedAllMsg:(nullable DTMentionedMsgInfo *)mentionedAllMsg
                  mentionedMeMsg:(nullable DTMentionedMsgInfo *)mentionedMeMsg
                   mentionsDraft:(nullable NSArray<DTMention *> *)mentionsDraft
              messageClearAnchor:(unsigned long long)messageClearAnchor
                    messageDraft:(nullable NSString *)messageDraft
                  mutedUntilDate:(nullable NSDate *)mutedUntilDate
                 plainTextEnable:(BOOL)plainTextEnable
              readPositionEntity:(nullable DTReadPositionEntity *)readPositionEntity
         removedFromConversation:(BOOL)removedFromConversation
                 shouldBeVisible:(BOOL)shouldBeVisible
                stickCallingDate:(nullable NSDate *)stickCallingDate
                       stickDate:(nullable NSDate *)stickDate
                    threadConfig:(nullable DTThreadConfigEntity *)threadConfig
            translateSettingType:(nullable NSNumber *)translateSettingType
                      unreadFlag:(unsigned int)unreadFlag
              unreadMessageCount:(NSUInteger)unreadMessageCount
                     unreadState:(NSUInteger)unreadState
            unreadTimeStimeStamp:(unsigned long long)unreadTimeStimeStamp
                      groupModel:(TSGroupModel *)groupModel
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:archivalDate:conversationEntity:creationDate:draftQuoteMessageId:expiresInSeconds:hasEverHadMessage:isArchived:lastMessageDate:lastestMsg:mentionedAllMsg:mentionedMeMsg:mentionsDraft:messageClearAnchor:messageDraft:mutedUntilDate:plainTextEnable:readPositionEntity:removedFromConversation:shouldBeVisible:stickCallingDate:stickDate:threadConfig:translateSettingType:unreadFlag:unreadMessageCount:unreadState:unreadTimeStimeStamp:groupModel:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithGroupModel:(TSGroupModel *)groupModel;


+ (instancetype)getOrCreateThreadWithGroupModel:(TSGroupModel *)groupModel;
+ (instancetype)getOrCreateThreadWithGroupModel:(TSGroupModel *)groupModel
                                    transaction:(SDSAnyWriteTransaction *)transaction;

+ (instancetype)getOrCreateThreadWithGroupId:(NSData *)groupId;
+ (instancetype)getOrCreateThreadWithGroupId:(NSData *)groupId
                                 transaction:(SDSAnyWriteTransaction *)transaction;
+ (instancetype)getOrCreateThreadWithGroupId:(NSData *)groupId
                                    generate:(BOOL *)generate
                                 transaction:(SDSAnyWriteTransaction *)transaction;

+ (instancetype _Nullable)threadWithGroupId:(NSData *)groupId transaction:(SDSAnyReadTransaction *)transaction;

+ (instancetype _Nullable)getThreadWithGroupId:(NSData *)groupId transaction:(SDSAnyReadTransaction *)transaction;

+ (nullable instancetype)getThreadWithGroupId:(NSData *)groupId;

+ (NSString *)threadIdFromGroupId:(NSData *)groupId;

- (BOOL)isLocalUserInGroup;
- (BOOL)isLocalUserInGroupWithTransaction:(SDSAnyReadTransaction *)transaction;

// all group threads containing recipient as a member
+ (NSArray<TSGroupThread *> *)groupThreadsWithRecipientId:(NSString *)recipientId
                                              transaction:(SDSAnyWriteTransaction *)transaction;

- (void)updateAvatarWithAttachmentStream:(TSAttachmentStream *)attachmentStream;
- (void)updateAvatarWithAttachmentStream:(TSAttachmentStream *)attachmentStream
                             transaction:(SDSAnyWriteTransaction *)transaction;

- (void)fireAvatarChangedNotification;

+ (nullable NSString *)transformToServerGroupIdWithLocalGroupId:(NSData *)groupId;
+ (nullable NSData *)transformToLocalGroupIdWithServerGroupId:(NSString *)groupId;

+ (NSData *)groupIdFromThreadId:(NSString *)threadId;

- (BOOL)validateGroupId:(NSData *)groupId;

- (BOOL)businessFromVega;

@end

NS_ASSUME_NONNULL_END
