//
//  DTChatFolderManager.h
//  TTServiceKit
//
//  Created by Ethan on 2022/4/19.
//

#import "BaseModel.h"
//#import <TTServiceKit/TTServiceKit.h>
#import "TSThread.h"
#import <Mantle/Mantle.h>

typedef NS_ENUM(NSInteger, DTFolderType) {
    DTFolderTypeRecommend,
    DTFolderTypeCustom,
};

typedef NS_ENUM(NSInteger, DTFolderThreadType) {
    DTFolderThreadTypeContact,
    DTFolderThreadTypeGroup
};

NS_ASSUME_NONNULL_BEGIN

extern NSString *const kChatFolderUpdateKey;
extern NSString *const kChatFolderUnreadKey;
extern NSString *const kChatFolderAtMeKey;
extern NSString *const kChatFolderPrivateKey;
extern NSString *const kChatFolderVegaKey;

static NSString *kChatFolderUniqueIdPrefix = @"difft_chat_folders_";

@protocol DTChatFolderManagerDelegate <NSObject>

- (void)chatFoldersChanged;

@end

@interface DTFolderThreadEntity : MTLModel<MTLJSONSerializing>

- (nullable instancetype)initWithThread:(TSThread *)thread;

@property (nonatomic, copy) NSString *id;
@property (nonatomic, assign) DTFolderThreadType type;

@end

@interface DTFolderConditions : MTLModel<MTLJSONSerializing>

@property (atomic, copy, nullable) NSString *keywords;
@property (atomic, copy, nullable) NSString *groupOwners;

@end

@interface DTChatFolderEntity : BaseModel<MTLJSONSerializing>

@property (nonatomic, copy) NSString *name;
@property (nonatomic, assign) DTFolderType folderType;
@property (nonatomic, strong) NSArray <DTFolderThreadEntity *> *cIds;
@property (atomic, strong, nullable) DTFolderConditions *conditions;
@property (nonatomic, assign) BOOL excludeFromAll;
//MARK: 以下字段不参与同步
@property (nonatomic, readonly) NSString *displayName;
@property (nonatomic, assign) NSInteger sortIndex;

- (nonnull instancetype)init;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                            cIds:(NSArray<DTFolderThreadEntity *> *)cIds
                      conditions:(nullable DTFolderConditions *)conditions
                  excludeFromAll:(BOOL)excludeFromAll
                      folderType:(DTFolderType)folderType
                            name:(NSString *)name
                       sortIndex:(NSInteger)sortIndex
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:cIds:conditions:excludeFromAll:folderType:name:sortIndex:));

// clang-format on

// --- CODE GENERATION MARKER

- (NSInteger)numberOfThreadsWithTransaction:(SDSAnyReadTransaction *)transaction;

- (BOOL)isContainThread:(TSThread *)thread transaction:(SDSAnyReadTransaction *)transaction;
- (BOOL)isConditonsContainThread:(TSThread *)thread transaction:(SDSAnyReadTransaction *)transaction;
- (BOOL)isManualContainThread:(TSThread *)thread;

@end

@class SDSAnyReadTransaction;
@class SDSAnyWriteTransaction;

@interface DTChatFolderManager : NSObject


@property (nonatomic, weak) id<DTChatFolderManagerDelegate> delegate;
@property (nonatomic, strong) NSArray <DTChatFolderEntity *> *chatFolders;
@property (nonatomic, assign) BOOL excludeVegaFromAll;

+ (instancetype)sharedManager;

+ (NSArray <NSString *> *)recommendKeys;
+ (NSString *)folderAllKey;
///剩余可创建folder数
+ (NSInteger)leftCount;

- (NSArray <DTChatFolderEntity *> *)fetchChatFolders;
- (NSArray <DTChatFolderEntity *> *)fetchChatFolders:(SDSAnyReadTransaction *)transaction;

+ (NSInteger)chatFolderVersion;
+ (void)updateChatFolderVersion:(NSInteger)version;

+ (TSThread *)getOrCreateThreadWithThreadId:(NSString *)threadId;
+ (TSThread *)getOrCreateThreadWithThreadId:(NSString *)threadId
                     transaction:(SDSAnyWriteTransaction *)transaction;

+ (TSThread *)getThreadWithThreadId:(NSString *)threadId;
+ (nullable TSThread *)getThreadWithThreadId:(NSString *)threadId
                        transaction:(SDSAnyReadTransaction *)transaction;

+ (void)saveChatFolders:(NSArray <DTChatFolderEntity *> *)chatFolders
                success:(void(^ _Nullable)(void))success
                failure:(void(^ _Nullable)(NSError *error))failure;

+ (void)updateChatFolders:(NSArray <DTChatFolderEntity *> *)chatFolders
              forceUpdate:(BOOL)forceUpdate
               newVersion:(NSInteger)newVersion
                  success:(void(^ _Nullable)(void))success;

+ (void)updateChatFolders:(NSArray <DTChatFolderEntity *> *)chatFolders
              forceUpdate:(BOOL)forceUpdate
               newVersion:(NSInteger)newVersion
                  success:(void(^ _Nullable)(void))success
              transaction:(SDSAnyWriteTransaction * _Nullable)transaction;

@end

NS_ASSUME_NONNULL_END
