//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "BaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@class Contact;
@class SignalRecipient;
@class SDSAnyReadTransaction;

// This class represents a single valid Signal account.
//
// * Contacts with multiple signal accounts will correspond to
//   multiple instances of SignalAccount.
// * For non-contacts, the contact property will be nil.
//
@interface SignalAccount : BaseModel

// An E164 value identifying the signal account.
//
// This is the key property of this class and it
// will always be non-null.
@property (nonatomic, readonly) NSString *recipientId;

// This property is optional and will not be set for
// non-contact account.
@property (nonatomic, nullable) Contact *contact;

@property (nonatomic) BOOL hasMultipleAccountContact;

// For contacts with more than one signal account,
// this is a label for the account.
@property (nonatomic) NSString *multipleAccountLabelText;

// added: a flag to identify a contact was added manually or user modified this contact remark name.
@property (nonatomic) BOOL isManualEdited;

// added: a remark name for a contact
@property (nonatomic, nullable) NSString *remarkName;

- (nullable NSString *)contactFullName;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                         contact:(nullable Contact *)contact
       hasMultipleAccountContact:(BOOL)hasMultipleAccountContact
                  isManualEdited:(BOOL)isManualEdited
        multipleAccountLabelText:(NSString *)multipleAccountLabelText
                     recipientId:(NSString *)recipientId
                      remarkName:(nullable NSString *)remarkName
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:contact:hasMultipleAccountContact:isManualEdited:multipleAccountLabelText:recipientId:remarkName:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithSignalRecipient:(SignalRecipient *)signalRecipient;

- (instancetype)initWithRecipientId:(NSString *)recipientId;

// In most cases this should be non-null. This should only
// be null in the case where the SignalRecipient was
// deleted before this property was accessed.
- (nullable SignalRecipient *)signalRecipientWithTransaction:(SDSAnyReadTransaction *)transaction;
- (BOOL)isEqualToSignalAccount:(SignalAccount *)signalAccount;
/// 是否显示Ext
+ (BOOL)isExt:(NSString *)recipientId;
+ (BOOL)isExt:(NSString *)recipientId transaction:(SDSAnyReadTransaction *)transaction;

- (BOOL)isBot;

- (BOOL)isLocalSignalAccount;

+ (nullable SignalAccount *)signalAccountWithRecipientId:(NSString *)recipientId transaction:(SDSAnyReadTransaction *)transaction;

@end

NS_ASSUME_NONNULL_END
