//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "DataSource.h"
#import "TSAttachment.h"

#if TARGET_OS_IPHONE
#import <UIKit/UIKit.h>

#endif

NS_ASSUME_NONNULL_BEGIN

@class DSKProtoAttachmentPointer;
@class TSAttachmentPointer;
@class SDSAnyWriteTransaction;

@interface TSAttachmentStream : TSAttachment

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                         albumId:(nullable NSString *)albumId
                  albumMessageId:(nullable NSString *)albumMessageId
            appearInMediaGallery:(BOOL)appearInMediaGallery
         attachmentSchemaVersion:(NSUInteger)attachmentSchemaVersion
                  attachmentType:(TSAttachmentType)attachmentType
                       byteCount:(unsigned int)byteCount
                     contentType:(NSString *)contentType
                   encryptionKey:(NSData *)encryptionKey
                    isDownloaded:(BOOL)isDownloaded
                        serverId:(unsigned long long)serverId
                  sourceFilename:(nullable NSString *)sourceFilename
      cachedAudioDurationSeconds:(nullable NSNumber *)cachedAudioDurationSeconds
               cachedImageHeight:(nullable NSNumber *)cachedImageHeight
                cachedImageWidth:(nullable NSNumber *)cachedImageWidth
               creationTimestamp:(NSDate *)creationTimestamp
                  decibelSamples:(nullable NSArray<NSNumber *> *)decibelSamples
                          digest:(nullable NSData *)digest
             encryptedDatalength:(NSInteger)encryptedDatalength
                      isUploaded:(BOOL)isUploaded
           lazyRestoreFragmentId:(nullable NSString *)lazyRestoreFragmentId
           localRelativeFilePath:(nullable NSString *)localRelativeFilePath
              serverAttachmentId:(NSString *)serverAttachmentId
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:albumId:albumMessageId:appearInMediaGallery:attachmentSchemaVersion:attachmentType:byteCount:contentType:encryptionKey:isDownloaded:serverId:sourceFilename:cachedAudioDurationSeconds:cachedImageHeight:cachedImageWidth:creationTimestamp:decibelSamples:digest:encryptedDatalength:isUploaded:lazyRestoreFragmentId:localRelativeFilePath:serverAttachmentId:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)init NS_UNAVAILABLE;
- (instancetype)initWithContentType:(NSString *)contentType
                          byteCount:(UInt32)byteCount
                     sourceFilename:(nullable NSString *)sourceFilename
                     albumMessageId:(nullable NSString *)albumMessageId
                            albumId:(nullable NSString *)albumId NS_DESIGNATED_INITIALIZER;

- (instancetype)initWithPointer:(TSAttachmentPointer *)pointer albumMessageId:(nullable NSString *)albumMessageId albumId:(nullable NSString *)albumId NS_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;

// Though now required, `digest` may be null for pre-existing records or from
// messages received from other clients
@property (nullable, nonatomic) NSData *digest;
@property (nonatomic, assign) NSInteger encryptedDatalength;

// This only applies for attachments being uploaded.
@property (atomic) BOOL isUploaded;

//record for report to server;
@property (atomic, copy) NSString *serverAttachmentId;

@property (nonatomic, readonly) NSDate *creationTimestamp;

@property (nullable, atomic, strong) NSArray<NSNumber *> *decibelSamples;
@property (nullable, atomic) NSNumber *cachedAudioDurationSeconds;

#if TARGET_OS_IPHONE
- (nullable UIImage *)image;
- (nullable UIImage *)thumbnailImage;
- (nullable NSData *)thumbnailData;
- (nullable NSData *)validStillImageData;
#endif

- (BOOL)isAnimated;
- (BOOL)isImage;
- (BOOL)isVideo;
- (BOOL)isAudio;
// TODO: rename to originalMediaURL 避免歧义
- (nullable NSURL *)mediaURL;

+ (BOOL)hasThumbnailForMimeType:(NSString *)contentType;

// TODO: rename to originalFilePath 避免歧义
- (nullable NSString *)filePath;
- (nullable NSString *)thumbnailPath;

- (nullable NSData *)readDataFromFileWithError:(NSError **)error;
- (BOOL)writeData:(NSData *)data error:(NSError **)error;
- (nullable NSData *)readEncryptedDataFromFileWithError:(NSError **)error;
- (BOOL)writeEncryptedData:(NSData *)data error:(NSError **)error;
- (void)removeVoicePlaintextFile;
- (BOOL)writeDataSource:(id <DataSource>)dataSource;

- (BOOL)isOversizeText;
- (nullable NSString *)readOversizeText;

+ (void)deleteAttachments;
+ (NSString *)attachmentsFolder;

- (BOOL)shouldHaveImageSize;
- (CGSize)imageSize;

- (CGFloat)audioDurationSeconds;
- (CGFloat)calculateAudioDurationSeconds;

+ (nullable NSError *)migrateToSharedData;

#pragma mark - Image Validation

- (BOOL)isValidImage;

#pragma mark - Update With... Methods

// Marks attachment as having completed "lazy backup restore."
- (void)updateWithLazyRestoreComplete;

- (nullable TSAttachmentStream *)cloneAsThumbnail;

#pragma mark - Protobuf

+ (nullable DSKProtoAttachmentPointer *)buildProtoForAttachmentId:(nullable NSString *)attachmentId;

- (DSKProtoAttachmentPointer *)buildProto;

@end

NS_ASSUME_NONNULL_END
