//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "TSAttachmentStream.h"
#import "MIMETypeUtil.h"
#import "NSData+Image.h"
#import "OWSFileSystem.h"
#import "SSKCryptography.h"
#import "TSAttachmentPointer.h"
#import <AVFoundation/AVFoundation.h>
#import <ImageIO/ImageIO.h>
#import <TTServiceKit/TTServiceKit-Swift.h>
#import <objc/runtime.h>

NS_ASSUME_NONNULL_BEGIN

NSErrorDomain const TSAttachmentStreamErrorDomain = @"TSAttachmentStreamErrorDomain";

@interface TSAttachmentStream ()

// We only want to generate the file path for this attachment once, so that
// changes in the file path generation logic don't break existing attachments.
@property (nullable, nonatomic) NSString *localRelativeFilePath;

// These properties should only be accessed while synchronized on self.
@property (nullable, nonatomic) NSNumber *cachedImageWidth;
@property (nullable, nonatomic) NSNumber *cachedImageHeight;


// Optional property.  Only set for attachments which need "lazy backup restore."
@property (nonatomic, nullable) NSString *lazyRestoreFragmentId;

// Transient guard used only while inserting a payload that is already a
// display-ready thumbnail. The insert hook runs synchronously on this instance.
@property (atomic) BOOL shouldSkipThumbnailGenerationOnInsert;

@end

/// Serves in-memory byte ranges to AVFoundation.
@interface TSAttachmentMemoryResourceLoader : NSObject <AVAssetResourceLoaderDelegate>
@property (nonatomic, readonly) NSData *data;
@property (nonatomic, readonly) NSString *contentType;
- (instancetype)initWithData:(NSData *)data contentType:(NSString *)contentType;
@end

@implementation TSAttachmentMemoryResourceLoader

- (instancetype)initWithData:(NSData *)data contentType:(NSString *)contentType
{
    self = [super init];
    if (!self) {
        return self;
    }
    _data = data;
    _contentType = contentType;
    return self;
}

- (BOOL)resourceLoader:(AVAssetResourceLoader *)resourceLoader
    shouldWaitForLoadingOfRequestedResource:(AVAssetResourceLoadingRequest *)loadingRequest
{
    AVAssetResourceLoadingContentInformationRequest *informationRequest = loadingRequest.contentInformationRequest;
    if (informationRequest) {
        informationRequest.contentType = [MIMETypeUtil utiTypeForMIMEType:self.contentType] ?: self.contentType;
        informationRequest.contentLength = (long long)self.data.length;
        informationRequest.byteRangeAccessSupported = YES;
    }

    AVAssetResourceLoadingDataRequest *dataRequest = loadingRequest.dataRequest;
    if (dataRequest) {
        long long start = dataRequest.currentOffset != 0 ? dataRequest.currentOffset : dataRequest.requestedOffset;
        if (start < 0 || start > (long long)self.data.length) {
            NSError *error = [NSError errorWithDomain:NSCocoaErrorDomain
                                                 code:NSFileReadCorruptFileError
                                             userInfo:nil];
            [loadingRequest finishLoadingWithError:error];
            return YES;
        }
        NSUInteger available = self.data.length - (NSUInteger)start;
        NSUInteger requested = (NSUInteger)MAX(0, dataRequest.requestedLength);
        NSUInteger length = dataRequest.requestsAllDataToEndOfResource ? available : MIN(available, requested);
        if (length > 0) {
            [dataRequest respondWithData:[self.data subdataWithRange:NSMakeRange((NSUInteger)start, length)]];
        }
    }

    [loadingRequest finishLoading];
    return YES;
}

@end

static void *TSAttachmentMemoryResourceLoaderAssociationKey = &TSAttachmentMemoryResourceLoaderAssociationKey;

#pragma mark -

@implementation TSAttachmentStream

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                         albumId:(nullable NSString *)albumId
                  albumMessageId:(nullable NSString *)albumMessageId
            appearInMediaGallery:(BOOL)appearInMediaGallery
         attachmentSchemaVersion:(NSUInteger)attachmentSchemaVersion
                  attachmentType:(TSAttachmentType)attachmentType
                       byteCount:(unsigned long long)byteCount
                     contentType:(NSString *)contentType
                   encryptionKey:(NSData *)encryptionKey
                          height:(unsigned int)height
                    isDownloaded:(BOOL)isDownloaded
               preprocessingKind:(TSAttachmentPreprocessingKind)preprocessingKind
             preprocessingParams:(nullable NSData *)preprocessingParams
                        serverId:(unsigned long long)serverId
                  sourceFilename:(nullable NSString *)sourceFilename
                           width:(unsigned int)width
      cachedAudioDurationSeconds:(nullable NSNumber *)cachedAudioDurationSeconds
               cachedImageHeight:(nullable NSNumber *)cachedImageHeight
                cachedImageWidth:(nullable NSNumber *)cachedImageWidth
               creationTimestamp:(NSDate *)creationTimestamp
                  decibelSamples:(nullable NSArray<NSNumber *> *)decibelSamples
                          digest:(nullable NSData *)digest
             encryptedDatalength:(NSInteger)encryptedDatalength
                      isUploaded:(BOOL)isUploaded
           lazyRestoreFragmentId:(nullable NSString *)lazyRestoreFragmentId
           localRelativeFilePath:(nullable NSString *)localRelativeFilePath
              serverAttachmentId:(NSString *)serverAttachmentId
{
    self = [super initWithGrdbId:grdbId
                        uniqueId:uniqueId
                           albumId:albumId
                    albumMessageId:albumMessageId
              appearInMediaGallery:appearInMediaGallery
           attachmentSchemaVersion:attachmentSchemaVersion
                    attachmentType:attachmentType
                         byteCount:byteCount
                       contentType:contentType
                     encryptionKey:encryptionKey
                            height:height
                      isDownloaded:isDownloaded
                 preprocessingKind:preprocessingKind
               preprocessingParams:preprocessingParams
                          serverId:serverId
                    sourceFilename:sourceFilename
                             width:width];

    if (!self) {
        return self;
    }

    _cachedAudioDurationSeconds = cachedAudioDurationSeconds;
    _cachedImageHeight = cachedImageHeight;
    _cachedImageWidth = cachedImageWidth;
    _creationTimestamp = creationTimestamp;
    _decibelSamples = decibelSamples;
    _digest = digest;
    _encryptedDatalength = encryptedDatalength;
    _isUploaded = isUploaded;
    _lazyRestoreFragmentId = lazyRestoreFragmentId;
    _localRelativeFilePath = localRelativeFilePath;
    _serverAttachmentId = serverAttachmentId;

    return self;
}

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithContentType:(NSString *)contentType
                          byteCount:(UInt64)byteCount
                     sourceFilename:(nullable NSString *)sourceFilename
                     albumMessageId:(nullable NSString *)albumMessageId
                            albumId:(nullable NSString *)albumId
{
    self = [super initWithContentType:contentType byteCount:byteCount sourceFilename:sourceFilename albumMessageId:albumMessageId albumId:albumId];
    if (!self) {
        return self;
    }

    self.isDownloaded = YES;
    // TSAttachmentStream doesn't have any "incoming vs. outgoing"
    // state, but this constructor is used only for new outgoing
    // attachments which haven't been uploaded yet.
    _isUploaded = NO;
    _creationTimestamp = [NSDate new];

    [self ensureFilePath];

    return self;
}

- (instancetype)initWithPointer:(TSAttachmentPointer *)pointer albumMessageId:(nullable NSString *)albumMessageId albumId:(nullable NSString *)albumId
{
    // Once saved, this AttachmentStream will replace the AttachmentPointer in the attachments collection.
    self = [super initWithPointer:pointer albumMessageId:albumMessageId albumId:albumId];
    if (!self) {
        return self;
    }

    _contentType = pointer.contentType;
    self.isDownloaded = YES;
    // TSAttachmentStream doesn't have any "incoming vs. outgoing"
    // state, but this constructor is used only for new incoming
    // attachments which don't need to be uploaded.
    _isUploaded = YES;
    _digest = pointer.digest;
    self.attachmentType = pointer.attachmentType;
    _creationTimestamp = [NSDate new];
    self.width = pointer.width;
    self.height = pointer.height;

    [self ensureFilePath];

    return self;
}

- (nullable instancetype)initWithCoder:(NSCoder *)coder
{
    self = [super initWithCoder:coder];
    if (!self) {
        return self;
    }

    // OWS105AttachmentFilePaths will ensure the file path is saved if necessary.
    [self ensureFilePath];

    // OWS105AttachmentFilePaths will ensure the creation timestamp is saved if necessary.
    if (!_creationTimestamp) {
        _creationTimestamp = [NSDate new];
    }

    // This is going to be slow the first time it runs.
    [self ensureThumbnail];

    return self;
}

#pragma mark - Any Transaction Hooks

- (void)anyDidInsertWithTransaction:(SDSAnyWriteTransaction *)transaction
{
    [super anyDidInsertWithTransaction:transaction];

    // Placeholder rows skip the synchronous decode — -[OWSMessageSender
    // enqueueMessage:] does it off-transaction and touches the owning message when
    // it lands. A concurrent compression can hold the hardware decoder for seconds
    // (~2s against a 4K encode), and holding the write lock that long stalls every
    // later bubble in a batch.
    if (self.preprocessingKind != TSAttachmentPreprocessingKindNone
        || self.shouldSkipThumbnailGenerationOnInsert) {
        return;
    }

    [self ensureThumbnail];
}

- (void)anyInsertPreparedThumbnailWithTransaction:(SDSAnyWriteTransaction *)transaction
{
    OWSAssertDebug(!self.shouldSkipThumbnailGenerationOnInsert);
    self.shouldSkipThumbnailGenerationOnInsert = YES;
    @try {
        [self anyInsertWithTransaction:transaction];
    } @finally {
        self.shouldSkipThumbnailGenerationOnInsert = NO;
    }
}

- (void)anyDidUpdateWithTransaction:(SDSAnyWriteTransaction *)transaction
{
    [super anyDidUpdateWithTransaction:transaction];

    [self ensureThumbnail];
}

- (void)anyDidRemoveWithTransaction:(SDSAnyWriteTransaction *)transaction{
    // 保留附件对应的信息，以后需要的时候可以再下载
//    [super anyDidRemoveWithTransaction:transaction];
    [self removeFileWithTransaction:transaction];
}



- (void)upgradeFromAttachmentSchemaVersion:(NSUInteger)attachmentSchemaVersion
{
    [super upgradeFromAttachmentSchemaVersion:attachmentSchemaVersion];

    if (attachmentSchemaVersion < 3) {
        // We want to treat any legacy TSAttachmentStream as though
        // they have already been uploaded.  If it needs to be reuploaded,
        // the OWSUploadingService will update this progress when the
        // upload begins.
        self.isUploaded = YES;
    }

    if (attachmentSchemaVersion < 4) {
        // Legacy image sizes don't correctly reflect image orientation.
        @synchronized(self)
        {
            self.cachedImageWidth = nil;
            self.cachedImageHeight = nil;
        }
    }
}

- (void)ensureFilePath
{
    if (self.localRelativeFilePath) {
        return;
    }

    NSString *attachmentsFolder = [[self class] attachmentsFolder];
    NSString *filePath = [MIMETypeUtil filePathForAttachment:self.uniqueId
                                                  ofMIMEType:self.contentType
                                              sourceFilename:self.sourceFilename
                                                    inFolder:attachmentsFolder];
    if (!filePath) {
        OWSFailDebug(@"%@ Could not generate path for attachment.", self.logTag);
        return;
    }
    if (![filePath hasPrefix:attachmentsFolder]) {
        OWSFailDebug(@"%@ Attachment paths should all be in the attachments folder.", self.logTag);
        return;
    }
    NSString *localRelativeFilePath = [filePath substringFromIndex:attachmentsFolder.length];
    if (localRelativeFilePath.length < 1) {
        OWSFailDebug(@"%@ Empty local relative attachment paths.", self.logTag);
        return;
    }

    self.localRelativeFilePath = localRelativeFilePath;
    OWSAssertDebug(self.filePath);
}

#pragma mark - File Management

- (nullable NSString *)encryptedFilePath {
    if (!self.filePath) {
        OWSFailDebug(@"%@ Missing path for encrypted attachment.", self.logTag);
        return nil;
    }
    return [NSString stringWithFormat:@"%@enc", self.filePath];
}

- (BOOL)isStoredEncrypted
{
    return self.hasEncryptedFile && self.hasUsableEncryptionMetadata;
}

- (BOOL)hasEncryptedFile
{
    NSString *_Nullable path = self.encryptedFilePath;
    return path.length > 0 && [[NSFileManager defaultManager] fileExistsAtPath:path];
}

- (BOOL)hasUsableEncryptionMetadata
{
    return self.encryptionKey.length >= 64 && self.digest.length > 0;
}

- (nullable NSData *)readDataFromFileWithError:(NSError **)error
{
    *error = nil;
    NSString *_Nullable filePath = self.filePath;
    if (!filePath) {
        OWSFailDebug(@"%@ Missing path for attachment.", self.logTag);
        return nil;
    }

    // A retained instance may not yet contain committed encryption metadata.
    if (self.hasEncryptedFile && !self.hasUsableEncryptionMetadata
        && ![[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
        *error = [NSError errorWithDomain:TSAttachmentStreamErrorDomain
                                     code:TSAttachmentStreamErrorMissingEncryptionMetadata
                                 userInfo:@{
                                     NSLocalizedDescriptionKey : @"Encrypted attachment metadata is not available on this model instance."
                                 }];
        return nil;
    }

    if (self.isStoredEncrypted) {
        NSData *_Nullable encryptedData = [self readEncryptedDataFromFileWithError:error];
        if (!encryptedData || *error) {
            return nil;
        }

        // Migrated ciphertext has a new IV; authenticate it with its local digest.
        NSData *localDigest = self.digest.length == 16
            ? [SSKCryptography computeMD5Digest:encryptedData]
            : [SSKCryptography computeSHA256Digest:encryptedData];
        NSError *decryptError = nil;
        NSData *_Nullable plaintext = [SSKCryptography decryptAttachment:encryptedData
                                                                  withKey:self.encryptionKey
                                                                   digest:localDigest
                                                               useMd5Hash:YES
                                                             unpaddedSize:(UInt32)self.byteCount
                                                                    error:&decryptError];
        if (decryptError) {
            *error = decryptError;
            return nil;
        }
        return plaintext;
    }

    NSData *_Nullable plaintext = [NSData dataWithContentsOfFile:filePath options:0 error:error];
    if (!plaintext || *error) {
        return nil;
    }

    // Lazily migrate uploaded plaintext left by older builds.
    if (self.isUploaded && self.encryptionKey.length >= 64 && self.digest.length > 0) {
        NSData *aesKey = [self.encryptionKey subdataWithRange:NSMakeRange(0, 32)];
        NSData *hmacKey = [self.encryptionKey subdataWithRange:NSMakeRange(32, 32)];
        NSData *outKey = nil;
        NSData *outDigest = nil;
        NSData *_Nullable ciphertext = [SSKCryptography encryptAttachmentData:plaintext
                                                                          eKey:aesKey
                                                                       hmacKey:hmacKey
                                                                        outKey:&outKey
                                                                     outDigest:&outDigest
                                                                    useMd5Hash:(self.digest.length == 16)];
        NSError *migrationError = nil;
        if (ciphertext && [self writeEncryptedData:ciphertext error:&migrationError]) {
            NSError *cleanupError = nil;
            BOOL removedPlaintext = [self removePlaintextFileWithError:&cleanupError];
            if (!removedPlaintext) {
                OWSLogError(@"%@ legacy plaintext cleanup failed after migration: %@", self.logTag, cleanupError);
            }
        } else {
            OWSLogError(@"%@ legacy plaintext migration failed: %@", self.logTag, migrationError);
        }
    }
    return plaintext;
}

- (nullable NSData *)decryptedData
{
    NSError *error = nil;
    NSData *_Nullable data = [self readDataFromFileWithError:&error];
    if ([error.domain isEqualToString:TSAttachmentStreamErrorDomain]
        && error.code == TSAttachmentStreamErrorMissingEncryptionMetadata) {
        // Refresh a retained pre-commit model outside the low-level read primitive.
        __block TSAttachmentStream *_Nullable latestStream = nil;
        [self.databaseStorage readWithBlock:^(SDSAnyReadTransaction *transaction) {
            latestStream = [TSAttachmentStream anyFetchAttachmentStreamWithUniqueId:self.uniqueId
                                                                          transaction:transaction];
        }];
        if (latestStream) {
            error = nil;
            data = [latestStream readDataFromFileWithError:&error];
        }
    }
    if (error) {
        OWSLogError(@"%@ failed to read attachment plaintext: %@", self.logTag, error);
    }
    return data;
}

- (BOOL)writeData:(NSData *)data error:(NSError **)error
{
    OWSAssertDebug(data);

    *error = nil;
    NSString *_Nullable filePath = self.filePath;
    if (!filePath) {
        OWSFailDebug(@"%@ Missing path for attachment.", self.logTag);
        return NO;
    }
    return [data writeToFile:filePath options:0 error:error];
}

- (nullable NSData *)readEncryptedDataFromFileWithError:(NSError **)error
{
    *error = nil;
    NSString *_Nullable filePath = [self encryptedFilePath];
    if (!filePath) {
        return nil;
    }
    return [NSData dataWithContentsOfFile:filePath options:0 error:error];
}

- (BOOL)writeEncryptedData:(NSData *)data error:(NSError **)error
{
    OWSAssertDebug(data);

    *error = nil;
    NSString *_Nullable filePath = [self encryptedFilePath];
    if (!filePath) {
        return NO;
    }
    BOOL success = [data writeToFile:filePath options:NSDataWritingAtomic error:error];
    if (success) {
        [[NSFileManager defaultManager]
            setAttributes:@{ NSFileProtectionKey : NSFileProtectionCompleteUntilFirstUserAuthentication }
            ofItemAtPath:filePath
            error:nil];
        NSURL *url = [NSURL fileURLWithPath:filePath];
        [url setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:nil];
    }
    return success;
}

- (BOOL)removeEncryptedDataWithError:(NSError **)error
{
    *error = nil;
    NSString *_Nullable filePath = [self encryptedFilePath];
    if (!filePath) {
        return NO;
    }
    
    if (![[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
        OWSLogWarn(@"%@ Encrypted file already removed: %@", self.logTag, filePath);
        return YES;
    }
    
    OWSLogInfo(@"%@ Removing encrypted attachment to file: %@", self.logTag, filePath);
    return [[NSFileManager defaultManager] removeItemAtPath:filePath error:error];
}

- (BOOL)writeDataSource:(id <DataSource>)dataSource
{
    OWSAssertDebug(dataSource);

    NSString *_Nullable filePath = self.filePath;
    if (!filePath) {
        OWSFailDebug(@"%@ Missing path for attachment.", self.logTag);
        return NO;
    }

    // On-disk sources: copyItemAtURL: (APFS CoW) instead of a full NSData read.
    // DataSourceValue is excluded — its dataUrl lazily writes a temp file.
    if ([dataSource isKindOfClass:[DataSourcePath class]]) {
        NSURL *_Nullable sourceURL = dataSource.dataUrl;
        if (sourceURL.isFileURL) {
            // A 0-byte source means the original is unreadable; copying it would
            // persist a corrupt attachment that downstream code can't diagnose.
            if (dataSource.dataLength == 0) {
                OWSFailDebug(@"%@ Source file is empty: %@", self.logTag, sourceURL.path);
                return NO;
            }

            // copyItemAtURL: refuses to overwrite; clear any partial leftover.
            [[NSFileManager defaultManager] removeItemAtPath:filePath error:nil];

            NSError *copyError = nil;
            if ([dataSource writeToUrl:[NSURL fileURLWithPath:filePath] error:&copyError]) {
                return YES;
            }
            OWSLogError(@"%@ Failed to copy attachment from %@: %@", self.logTag, sourceURL.path, copyError);
            return NO;
        }
    }

    return [dataSource writeToPath:filePath];
}

+ (NSString *)legacyAttachmentsDirPath
{
    return [[OWSFileSystem appDocumentDirectoryPath] stringByAppendingPathComponent:@"Attachments"];
}

+ (NSString *)sharedDataAttachmentsDirPath
{
    return [[OWSFileSystem appSharedDataDirectoryPath] stringByAppendingPathComponent:@"Attachments"];
}

+ (nullable NSError *)migrateToSharedData
{
    OWSLogInfo(@"%@ %s", self.logTag, __PRETTY_FUNCTION__);

    return [OWSFileSystem moveAppFilePath:self.legacyAttachmentsDirPath
                       sharedDataFilePath:self.sharedDataAttachmentsDirPath];
}

+ (NSString *)attachmentsFolder
{
    static NSString *attachmentsFolder = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        attachmentsFolder = TSAttachmentStream.sharedDataAttachmentsDirPath;

        [OWSFileSystem ensureDirectoryExists:attachmentsFolder];
    });
    return attachmentsFolder;
}

- (nullable NSString *)filePath
{
    if (!self.localRelativeFilePath) {
        OWSFailDebug(@"%@ Attachment missing local file path.", self.logTag);
        return nil;
    }

    return [[[self class] attachmentsFolder] stringByAppendingPathComponent:self.localRelativeFilePath];
}

- (nullable NSString *)thumbnailPath
{
    NSString *filePath = self.filePath;
    if (!filePath) {
        OWSFailDebug(@"%@ Attachment missing local file path.", self.logTag);
        return nil;
    }

    if (!self.isImage && !self.isVideo && !self.isAnimated) {
        return nil;
    }

    NSString *filename = filePath.lastPathComponent.stringByDeletingPathExtension;
    NSString *containingDir = filePath.stringByDeletingLastPathComponent;
    NSString *newFilename = [filename stringByAppendingString:@"-signal-ios-thumbnail"];

    return [[containingDir stringByAppendingPathComponent:newFilename] stringByAppendingPathExtension:@"jpg"];
}

- (nullable NSURL *)mediaURL
{
    NSString *_Nullable filePath = self.filePath;
    if (!filePath) {
        OWSFailDebug(@"%@ Missing path for attachment.", self.logTag);
        return nil;
    }
    if (![[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
        return nil;
    }
    return [NSURL fileURLWithPath:filePath];
}

- (void)removeFileWithTransaction:(SDSAnyWriteTransaction *)transaction
{
    NSError *error;

    NSString *_Nullable thumbnailPath = self.thumbnailPath;
    if (thumbnailPath) {
        [[NSFileManager defaultManager] removeItemAtPath:thumbnailPath error:&error];

        if (error) {
            OWSLogError(@"%@ remove thumbnail errored with: %@", self.logTag, error);
        }
    }

    NSString *_Nullable filePath = self.filePath;
    if (!filePath) {
        OWSFailDebug(@"%@ Missing path for attachment.", self.logTag);
        return;
    }
    [[NSFileManager defaultManager] removeItemAtPath:filePath error:&error];

    if (error) {
        OWSLogError(@"%@ remove file errored with: %@", self.logTag, error);
    }
    
    [self removeEncryptedDataWithError:&error];
    if (error) {
        OWSLogError(@"%@ remove encrypted file errored with: %@", self.logTag, error);
    }
}

- (void)removeVoicePlaintextFile
{
    if (!self.isVoiceMessage) {
        OWSLogDebug(@"%@ is not a voice file.", self.logTag);
        return;
    }
    
    NSString *_Nullable encFilePath = [self encryptedFilePath];
    if (!encFilePath) {
        OWSLogInfo(@"%@ encFilePath is empty.", self.logTag);
        return;
    }
    
    if (![[NSFileManager defaultManager] fileExistsAtPath:encFilePath]) {
        OWSLogDebug(@"%@ File not exists for encFilePath.", self.logTag);
        return;
    }
    
    NSError *error;

    NSString *_Nullable filePath = self.filePath;
    if (!filePath) {
        OWSLogDebug(@"%@ Missing path for attachment.", self.logTag);
        return;
    }
    
    if (![[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
        OWSLogDebug(@"%@ File not exists for filePath.", self.logTag);
        return;
    }
    
    [[NSFileManager defaultManager] removeItemAtPath:filePath error:&error];

    if (error) {
        OWSLogError(@"%@ remove file errored with: %@", self.logTag, error);
    }
}

- (BOOL)removePlaintextFileWithError:(NSError **)error
{
    *error = nil;
    NSString *_Nullable filePath = self.filePath;
    if (filePath.length > 0 && [[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
        NSError *removeError = nil;
        if (![[NSFileManager defaultManager] removeItemAtPath:filePath error:&removeError]) {
            OWSLogError(@"%@ failed to remove plaintext attachment: %@", self.logTag, removeError);
            *error = removeError;
        }
    }
    NSString *_Nullable thumbnailPath = self.thumbnailPath;
    if (thumbnailPath.length > 0 && [[NSFileManager defaultManager] fileExistsAtPath:thumbnailPath]) {
        NSError *thumbnailError = nil;
        if (![[NSFileManager defaultManager] removeItemAtPath:thumbnailPath error:&thumbnailError]) {
            OWSLogError(@"%@ failed to remove plaintext attachment thumbnail: %@", self.logTag, thumbnailError);
            if (!*error) {
                *error = thumbnailError;
            }
        }
    }
    return *error == nil;
}

- (void)removePlaintextFile
{
    NSError *error = nil;
    (void)[self removePlaintextFileWithError:&error];
}

/// Returns a URL-safe extension for the in-memory asset.
- (NSString *)sanitizedAssetPathExtension
{
    NSMutableCharacterSet *allowed = [[NSCharacterSet alphanumericCharacterSet] mutableCopy];
    [allowed formIntersectionWithCharacterSet:[NSCharacterSet characterSetWithRange:NSMakeRange(0, 128)]];

    NSArray<NSString *> *candidates = @[
        self.sourceFilename.pathExtension ?: @"",
        [MIMETypeUtil fileExtensionForMIMEType:self.contentType] ?: @"",
    ];
    for (NSString *candidate in candidates) {
        if (candidate.length < 1) {
            continue;
        }
        NSString *filtered = [[candidate componentsSeparatedByCharactersInSet:[allowed invertedSet]]
            componentsJoinedByString:@""];
        if (filtered.length > 0) {
            return filtered.lowercaseString;
        }
    }
    return @"bin";
}

- (nullable AVAsset *)decryptedMediaAsset
{
    if (!self.hasEncryptedFile && !self.hasUsableEncryptionMetadata) {
        NSURL *_Nullable mediaURL = self.mediaURL;
        if (mediaURL) {
            return [AVURLAsset URLAssetWithURL:mediaURL options:nil];
        }
    }

    NSData *_Nullable data = self.decryptedData;
    if (!data) {
        OWSLogError(@"%@ failed to read encrypted media.", self.logTag);
        return nil;
    }

    // AVFoundation uses the extension for type inference.
    NSString *extension = [self sanitizedAssetPathExtension];
    NSURL *_Nullable url = [NSURL URLWithString:[NSString stringWithFormat:@"temptalk-attachment://%@/payload.%@",
                                                                           self.uniqueId,
                                                                           extension]];
    if (!url) {
        OWSLogError(@"%@ could not build a memory asset URL for attachment: %@", self.logTag, self.uniqueId);
        return nil;
    }
    AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
    TSAttachmentMemoryResourceLoader *loader =
        [[TSAttachmentMemoryResourceLoader alloc] initWithData:data contentType:self.contentType];
    dispatch_queue_t queue =
        dispatch_queue_create("com.difft.temptalk.attachment-resource-loader", DISPATCH_QUEUE_SERIAL);
    [asset.resourceLoader setDelegate:loader queue:queue];
    objc_setAssociatedObject(asset,
                             TSAttachmentMemoryResourceLoaderAssociationKey,
                             loader,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    return asset;
}

- (BOOL)isAnimated {
    return [MIMETypeUtil isAnimated:self.contentType];
}

- (BOOL)isImage {
    return [MIMETypeUtil isImage:self.contentType];
}

- (BOOL)isVideo {
    return [MIMETypeUtil isVideo:self.contentType];
}

- (BOOL)isAudio {
    return [MIMETypeUtil isAudio:self.contentType];
}

#pragma mark - Image Validation

- (BOOL)isValidImageWithData:(NSData *)data
{
    OWSAssertDebug(self.isImage || self.isAnimated);
    OWSAssertDebug(data);
    
    if (!data) {
        return NO;
    }

    return [data ows_isValidImageWithMimeType:self.contentType];
}

- (BOOL)isValidImage
{
    OWSAssertDebug(self.isImage || self.isAnimated);
    NSError *error = nil;
    NSData *_Nullable data = [self readDataFromFileWithError:&error];
    return data && !error && [self isValidImageWithData:data];
}

#pragma mark -

- (nullable UIImage *)image
{
    if ([self isVideo]) {
        return [self videoStillImage];
    } else if ([self isImage] || [self isAnimated]) {
        NSError *error = nil;
        NSData *data = [self readDataFromFileWithError:&error];
        if (!data) {
            return nil;
        }
        if (![self isValidImageWithData:data]) {
            return nil;
        }
        return [UIImage imageWithData:data];
    } else {
        return nil;
    }
}

- (nullable NSData *)validStillImageData
{
    if ([self isVideo]) {
        OWSFailDebug(@"%@ in %s isVideo was unexpectedly true", self.logTag, __PRETTY_FUNCTION__);
        return nil;
    }
    if ([self isAnimated]) {
        OWSFailDebug(@"%@ in %s isAnimated was unexpectedly true", self.logTag, __PRETTY_FUNCTION__);
        return nil;
    }

    NSError *error = nil;
    NSData *data = [self readDataFromFileWithError:&error];
    if (!data) {
        return nil;
    }
    if (![self isValidImageWithData:data]) {
        return nil;
    }

    return data;
}

+ (BOOL)hasThumbnailForMimeType:(NSString *)contentType
{
    return ([MIMETypeUtil isVideo:contentType] || [MIMETypeUtil isImage:contentType] ||
        [MIMETypeUtil isAnimated:contentType]);
}

- (nullable UIImage *)thumbnailImage
{
    if (self.isStoredEncrypted) {
        if (self.isVideo) {
            return [self videoStillImageWithMaxSize:CGSizeMake(512, 512)];
        }
        UIImage *_Nullable image = self.image;
        if (!image) {
            return nil;
        }
        CGSize size = image.size;
        CGFloat scale = MIN(1, 512 / MAX(size.width, size.height));
        CGSize target = CGSizeMake(MAX(1, floor(size.width * scale)), MAX(1, floor(size.height * scale)));
        UIGraphicsBeginImageContextWithOptions(target, NO, 1);
        [image drawInRect:CGRectMake(0, 0, target.width, target.height)];
        UIImage *thumbnail = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        return thumbnail;
    }

    NSString *thumbnailPath = self.thumbnailPath;
    if (!thumbnailPath) {
        OWSAssertDebug(!self.isImage && !self.isVideo && !self.isAnimated);

        return nil;
    }

    if (![[NSFileManager defaultManager] fileExistsAtPath:thumbnailPath]) {
        // This isn't true for some useful edge cases tested by the Debug UI.
        OWSLogError(@"%@ missing thumbnail for attachmentId: %@", self.logTag, self.uniqueId);

        return nil;
    }

    return [UIImage imageWithContentsOfFile:self.thumbnailPath];
}

- (nullable NSData *)thumbnailData
{
    if (self.isStoredEncrypted) {
        UIImage *_Nullable thumbnail = self.thumbnailImage;
        return thumbnail ? UIImageJPEGRepresentation(thumbnail, 0.9) : nil;
    }

    NSString *thumbnailPath = self.thumbnailPath;
    if (!thumbnailPath) {
        OWSAssertDebug(!self.isImage && !self.isVideo && !self.isAnimated);

        return nil;
    }

    if (![[NSFileManager defaultManager] fileExistsAtPath:thumbnailPath]) {
        OWSFailDebug(@"%@ missing thumbnail for attachmentId: %@", self.logTag, self.uniqueId);

        return nil;
    }

    return [NSData dataWithContentsOfFile:self.thumbnailPath];
}

- (void)ensureThumbnail
{
    // Never create a plaintext disk thumbnail once ciphertext exists.
    if (self.hasEncryptedFile) {
        return;
    }

    NSString *thumbnailPath = self.thumbnailPath;
    if (!thumbnailPath) {
        return;
    }

    if ([[NSFileManager defaultManager] fileExistsAtPath:thumbnailPath]) {
        // already exists
        return;
    }

    NSURL *_Nullable mediaURL = self.mediaURL;
    if (!mediaURL || ![[NSFileManager defaultManager] fileExistsAtPath:mediaURL.path]) {
        return;
    }

    CGFloat thumbnailSize = 512;

    UIImage *_Nullable result;
    if (self.isImage || self.isAnimated) {
        if (![self isValidImage]) {
            OWSLogWarn(@"%@ skipping thumbnail generation for invalid image at path: %@", self.logTag, self.filePath);
            return;
        }

        // Validation may migrate and remove the plaintext source.
        if (self.hasEncryptedFile) {
            return;
        }

        CGImageSourceRef imageSource = CGImageSourceCreateWithURL((__bridge CFURLRef)mediaURL, NULL);
        if (!imageSource) {
            OWSLogError(@"%@ could not open thumbnail source: %@", self.logTag, self.uniqueId);
            return;
        }
        NSDictionary *imageOptions = @{
            (NSString const *)kCGImageSourceCreateThumbnailFromImageIfAbsent : (NSNumber const *)kCFBooleanTrue,
            (NSString const *)kCGImageSourceThumbnailMaxPixelSize : @(thumbnailSize),
            (NSString const *)kCGImageSourceCreateThumbnailWithTransform : (NSNumber const *)kCFBooleanTrue
        };
        CGImageRef thumbnail
            = CGImageSourceCreateThumbnailAtIndex(imageSource, 0, (__bridge CFDictionaryRef)imageOptions);
        CFRelease(imageSource);

        if (!thumbnail) {
            OWSLogError(@"%@ could not decode thumbnail source: %@", self.logTag, self.uniqueId);
            return;
        }

        result = [[UIImage alloc] initWithCGImage:thumbnail];
        CGImageRelease(thumbnail);

    } else if (self.isVideo) {
        result = [self videoStillImageWithMaxSize:CGSizeMake(thumbnailSize, thumbnailSize)];
    } else {
        OWSFailDebug(@"%@ trying to generate thumnail for unexpected attachment: %@ of type: %@",
            self.logTag,
            self.uniqueId,
            self.contentType);
    }

    if (result == nil) {
        OWSFailDebug(@"%@ Unable to build thumbnail for attachmentId: %@", self.logTag, self.uniqueId);
        return;
    }

    NSData *thumbnailData = UIImageJPEGRepresentation(result, 0.9);

    OWSAssertDebug(thumbnailData.length > 0);
    OWSLogDebug(@"%@ generated thumbnail with size: %lu", self.logTag, (unsigned long)thumbnailData.length);
    [thumbnailData writeToFile:thumbnailPath atomically:YES];
}

- (nullable UIImage *)videoStillImage
{
    // Uses the assets intrinsic size by default
    return [self videoStillImageWithMaxSize:CGSizeZero];
}

- (nullable UIImage *)videoStillImageWithMaxSize:(CGSize)maxSize
{
    if (self.isStoredEncrypted && NSThread.isMainThread) {
        OWSLogError(@"%@ Refusing to synchronously generate an encrypted video still on the main thread.",
            self.logTag);
        return nil;
    }

    if (self.isStoredEncrypted) {
        // Do not read result if the completion may still be writing it.
        NSObject *resultLock = [NSObject new];
        __block UIImage *_Nullable result = nil;
        dispatch_semaphore_t semaphore = dispatch_semaphore_create(0);
        [self videoStillImageWithMaxSize:maxSize
                              completion:^(UIImage *_Nullable image) {
                                  @synchronized(resultLock) {
                                      result = image;
                                  }
                                  dispatch_semaphore_signal(semaphore);
                              }];
        if (dispatch_semaphore_wait(semaphore, dispatch_time(DISPATCH_TIME_NOW, 11 * NSEC_PER_SEC)) != 0) {
            OWSLogError(@"%@ Timed out waiting for encrypted video still: %@", self.logTag, self.uniqueId);
            return nil;
        }
        @synchronized(resultLock) {
            return result;
        }
    }

    AVAsset *_Nullable asset = [self decryptedMediaAsset];
    if (!asset) {
        return nil;
    }

    AVAssetImageGenerator *generator = [[AVAssetImageGenerator alloc] initWithAsset:asset];
    generator.maximumSize = maxSize;
    generator.appliesPreferredTrackTransform = YES;
    NSError *_Nullable error = nil;
    CMTime time = CMTimeMake(1, 60);
    CGImageRef _Nullable imageRef = [generator copyCGImageAtTime:time actualTime:NULL error:&error];
    if (!imageRef) {
        OWSLogError(@"%@ Failed to generate video still for attachment %@: %@", self.logTag, self.uniqueId, error);
        return nil;
    }

    UIImage *image = [[UIImage alloc] initWithCGImage:imageRef];
    CGImageRelease(imageRef);
    return image;
}

- (void)videoStillImageWithMaxSize:(CGSize)maxSize
                        completion:(void (^)(UIImage *_Nullable image))completion
{
    OWSAssertDebug(completion);

    NSObject *completionLock = [NSObject new];
    __block BOOL hasCompleted = NO;
    __block AVAsset *_Nullable activeAsset = nil;
    __block AVAssetImageGenerator *_Nullable activeGenerator = nil;

    void (^finish)(UIImage *_Nullable) = ^(UIImage *_Nullable image) {
        @synchronized(completionLock) {
            if (hasCompleted) {
                return;
            }
            hasCompleted = YES;
            activeAsset = nil;
            activeGenerator = nil;
        }
        completion(image);
    };

    // Bound the operation and suppress late duplicate completions.
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 10 * NSEC_PER_SEC),
        dispatch_get_global_queue(QOS_CLASS_UTILITY, 0),
        ^{
            AVAsset *_Nullable asset = nil;
            AVAssetImageGenerator *_Nullable generator = nil;
            @synchronized(completionLock) {
                if (hasCompleted) {
                    return;
                }
                hasCompleted = YES;
                asset = activeAsset;
                generator = activeGenerator;
                activeAsset = nil;
                activeGenerator = nil;
            }
            [asset cancelLoading];
            [generator cancelAllCGImageGeneration];
            OWSLogError(@"%@ Timed out asynchronously generating video still for attachment: %@",
                self.logTag,
                self.uniqueId);
            completion(nil);
        });

    dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
        AVAsset *_Nullable asset = [self decryptedMediaAsset];
        if (!asset) {
            finish(nil);
            return;
        }

        @synchronized(completionLock) {
            if (hasCompleted) {
                [asset cancelLoading];
                return;
            }
            activeAsset = asset;
        }

        NSArray<NSString *> *keys = @[ @"tracks" ];
        [asset loadValuesAsynchronouslyForKeys:keys
                             completionHandler:^{
                                 for (NSString *key in keys) {
                                     NSError *_Nullable loadingError = nil;
                                     if ([asset statusOfValueForKey:key error:&loadingError] != AVKeyValueStatusLoaded) {
                                         OWSLogError(@"%@ Failed to load video metadata key %@ for attachment %@: %@",
                                             self.logTag,
                                             key,
                                             self.uniqueId,
                                             loadingError);
                                         finish(nil);
                                         return;
                                     }
                                 }

                                 AVAssetImageGenerator *generator =
                                     [[AVAssetImageGenerator alloc] initWithAsset:asset];
                                 generator.maximumSize = maxSize;
                                 generator.appliesPreferredTrackTransform = YES;
                                 @synchronized(completionLock) {
                                     if (hasCompleted) {
                                         [generator cancelAllCGImageGeneration];
                                         return;
                                     }
                                     activeGenerator = generator;
                                 }

                                 CMTime time = CMTimeMake(1, 60);
                                 [generator generateCGImagesAsynchronouslyForTimes:@[ [NSValue valueWithCMTime:time] ]
                                                                 completionHandler:^(CMTime requestedTime,
                                                                     CGImageRef _Nullable imageRef,
                                                                     CMTime actualTime,
                                                                     AVAssetImageGeneratorResult result,
                                                                     NSError *_Nullable error) {
                                                                     if (result != AVAssetImageGeneratorSucceeded
                                                                         || !imageRef) {
                                                                         OWSLogError(@"%@ Failed to asynchronously generate video still for attachment %@: %@",
                                                                             self.logTag,
                                                                             self.uniqueId,
                                                                             error);
                                                                         finish(nil);
                                                                         return;
                                                                     }
                                                                     finish([[UIImage alloc] initWithCGImage:imageRef]);
                                                                 }];
                             }];
    });
}

+ (void)deleteAttachments
{
    NSError *error;
    NSFileManager *fileManager = [NSFileManager defaultManager];

    NSURL *fileURL = [NSURL fileURLWithPath:self.attachmentsFolder];
    NSArray<NSURL *> *contents =
        [fileManager contentsOfDirectoryAtURL:fileURL includingPropertiesForKeys:nil options:0 error:&error];

    if (error) {
        OWSFailDebug(@"failed to get contents of attachments folder: %@ with error: %@", self.attachmentsFolder, error);
        return;
    }

    for (NSURL *url in contents) {
        [fileManager removeItemAtURL:url error:&error];
        if (error) {
            OWSFailDebug(@"failed to remove item at path: %@ with error: %@", url, error);
        }
    }
}

- (CGSize)calculateImageSize
{
    if ([self isVideo]) {
        // Last resort — decodes a full frame just to measure it. Rows written by the
        // sender carry width/height, so -imageSize doesn't reach here for them.
        return [self videoStillImage].size;
    } else if ([self isImage] || [self isAnimated]) {
        NSError *error = nil;
        NSData *_Nullable data = [self readDataFromFileWithError:&error];
        if (!data || error) {
            return CGSizeZero;
        }
        if (![self isValidImage]) {
            return CGSizeZero;
        }

        // With CGImageSource we avoid loading the whole image into memory.
        CGImageSourceRef source = CGImageSourceCreateWithData((CFDataRef)data, NULL);
        if (!source) {
            OWSFailDebug(@"%@ Could not load image data", self.logTag);
            return CGSizeZero;
        }

        NSDictionary *options = @{
            (NSString *)kCGImageSourceShouldCache : @(NO),
        };
        NSDictionary *properties
            = (__bridge_transfer NSDictionary *)CGImageSourceCopyPropertiesAtIndex(source, 0, (CFDictionaryRef)options);
        CGSize imageSize = CGSizeZero;
        if (properties) {
            NSNumber *orientation = properties[(NSString *)kCGImagePropertyOrientation];
            NSNumber *width = properties[(NSString *)kCGImagePropertyPixelWidth];
            NSNumber *height = properties[(NSString *)kCGImagePropertyPixelHeight];

            if (width && height) {
                imageSize = CGSizeMake(width.floatValue, height.floatValue);

                if (orientation) {
                    imageSize =
                        [self applyImageOrientation:(UIImageOrientation)orientation.intValue toImageSize:imageSize];
                }
            } else {
                OWSFailDebug(@"%@ Could not determine image size", self.logTag);
            }
        }
        CFRelease(source);
        return imageSize;
    } else {
        return CGSizeZero;
    }
}

- (CGSize)applyImageOrientation:(UIImageOrientation)orientation toImageSize:(CGSize)imageSize
{
    switch (orientation) {
        case UIImageOrientationUp: // EXIF = 1
        case UIImageOrientationUpMirrored: // EXIF = 2
        case UIImageOrientationDown: // EXIF = 3
        case UIImageOrientationDownMirrored: // EXIF = 4
            return imageSize;
        case UIImageOrientationLeftMirrored: // EXIF = 5
        case UIImageOrientationLeft: // EXIF = 6
        case UIImageOrientationRightMirrored: // EXIF = 7
        case UIImageOrientationRight: // EXIF = 8
            return CGSizeMake(imageSize.height, imageSize.width);
        default:
            return imageSize;
    }
}

- (BOOL)shouldHaveImageSize
{
    return ([self isVideo] || [self isImage] || [self isAnimated]);
}

- (CGSize)imageSize
{
    OWSAssertDebug(self.shouldHaveImageSize);

    @synchronized(self)
    {
        if (self.cachedImageWidth && self.cachedImageHeight) {
            return CGSizeMake(self.cachedImageWidth.floatValue, self.cachedImageHeight.floatValue);
        }

        CGSize imageSize = CGSizeZero;
        if (self.width > 0 && self.height > 0) {
            imageSize = CGSizeMake(self.width, self.height);
        } else {
            imageSize = [self calculateImageSize];
        }
        
        if (imageSize.width <= 0 || imageSize.height <= 0) {
            return CGSizeZero;
        }
        self.cachedImageWidth = @(imageSize.width);
        self.cachedImageHeight = @(imageSize.height);

        DatabaseStorageAsyncWrite(self.databaseStorage, ^(SDSAnyWriteTransaction *transaction) {

            TSAttachmentStream *latestInstance = [TSAttachmentStream anyFetchAttachmentStreamWithUniqueId:self.uniqueId transaction:transaction];
            if (latestInstance) {
                [latestInstance anyUpdateAttachmentStreamWithTransaction:transaction
                                                                   block:^(TSAttachmentStream * instance) {
                    instance.cachedImageWidth = @(imageSize.width);
                    instance.cachedImageHeight = @(imageSize.height);
                }];
            } else {
                // This message has not yet been saved or has been deleted; do nothing.
                // This isn't an error per se, but these race conditions should be
                // _very_ rare.
                OWSFailDebug(@"%@ Attachment not yet saved.", self.logTag);
            }
        });

        return imageSize;
    }
}

- (CGFloat)calculateAudioDurationSeconds
{
    OWSAssertIsOnMainThread();
    OWSAssertDebug([self isAudio]);

    NSError *error = nil;
    AVAudioPlayer *audioPlayer = nil;
    if (self.isStoredEncrypted) {
        NSData *_Nullable data = [self readDataFromFileWithError:&error];
        if (data) {
            audioPlayer = [[AVAudioPlayer alloc] initWithData:data error:&error];
        }
    } else {
        audioPlayer = [[AVAudioPlayer alloc] initWithContentsOfURL:self.mediaURL error:&error];
    }
    if (error && [error.domain isEqualToString:NSOSStatusErrorDomain]
        && (error.code == kAudioFileInvalidFileError || error.code == kAudioFileStreamError_InvalidFile)) {
        // Ignore "invalid audio file" errors.
        return 0.f;
    }
    if (!error) {
        return (CGFloat)[audioPlayer duration];
    } else {
        OWSLogError(@"Could not find audio duration: %@", error);
        return 0;
    }
}

- (CGFloat)audioDurationSeconds
{
    OWSAssertIsOnMainThread();

    if (self.cachedAudioDurationSeconds) {
        return self.cachedAudioDurationSeconds.floatValue;
    }

    CGFloat audioDurationSeconds = [self calculateAudioDurationSeconds];
    self.cachedAudioDurationSeconds = @(audioDurationSeconds);

    DatabaseStorageWrite(self.databaseStorage, ^(SDSAnyWriteTransaction *transaction) {
        TSAttachmentStream *latestInstance = [TSAttachmentStream anyFetchAttachmentStreamWithUniqueId:self.uniqueId transaction:transaction];
        if (latestInstance) {
            latestInstance.cachedAudioDurationSeconds = @(audioDurationSeconds);
            [latestInstance anyInsertWithTransaction:transaction];
        } else {
            // This message has not yet been saved or has been deleted; do nothing.
            // This isn't an error per se, but these race conditions should be
            // _very_ rare.
            OWSFailDebug(@"%@ Attachment not yet saved.", self.logTag);
        }
    });

    return audioDurationSeconds;
}

- (BOOL)isOversizeText
{
    return [self.contentType isEqualToString:OWSMimeTypeOversizeTextMessage];
}

- (nullable NSString *)readOversizeText
{
    if (!self.isOversizeText) {
        OWSFailDebug(@"%@ oversize text attachment has unexpected content type.", self.logTag);
        return nil;
    }
    NSError *error;
    NSData *_Nullable data = [self readDataFromFileWithError:&error];
    if (error || !data) {
        OWSFailDebug(@"%@ could not read oversize text attachment: %@.", self.logTag, error);
        return nil;
    }
    NSString *_Nullable string = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    return string;
}

#pragma mark - Update With... Methods

- (void)updateWithLazyRestoreComplete
{
    DatabaseStorageWrite(self.databaseStorage, ^(SDSAnyWriteTransaction *transaction) {
        [self anyUpdateAttachmentStreamWithTransaction:transaction
                                                 block:^(TSAttachmentStream * attachment) {
            [attachment setLazyRestoreFragmentId:nil];
        }];
    });
}

- (nullable TSAttachmentStream *)cloneAsThumbnail
{
    NSData *thumbnailData = self.thumbnailData;
    //  Only some media types have thumbnails
    if (!thumbnailData) {
        return nil;
    }

    // Copy the thumbnail to a new attachment.
    NSString *thumbnailName = [NSString stringWithFormat:@"quoted-thumbnail-%@", self.sourceFilename];
    TSAttachmentStream *thumbnailAttachment =
        [[TSAttachmentStream alloc] initWithContentType:OWSMimeTypeImageJpeg
                                              byteCount:(uint64_t)thumbnailData.length
                                         sourceFilename:thumbnailName albumMessageId:nil
                                                albumId:nil];

    NSError *error;
    BOOL success = [thumbnailAttachment writeData:thumbnailData error:&error];
    if (!success || error) {
        OWSLogError(@"%@ Couldn't copy attachment data for message sent to self: %@.", self.logTag, error);
        return nil;
    }

    return thumbnailAttachment;
}

// MARK: Protobuf serialization

+ (nullable DSKProtoAttachmentPointer *)buildProtoForAttachmentId:(nullable NSString *)attachmentId
{
    OWSAssertDebug(attachmentId.length > 0);

    // TODO we should past in a transaction, rather than sneakily generate one in `fetch...` to make sure we're
    // getting a consistent view in the message sending process. A brief glance shows it touches quite a bit of code,
    // but should be straight forward.
    __block TSAttachment *attachment= nil;
    [self.databaseStorage readWithBlock:^(SDSAnyReadTransaction * _Nonnull readTransaction) {
        attachment = [TSAttachmentStream anyFetchWithUniqueId:attachmentId transaction:readTransaction];
    }];
    if (![attachment isKindOfClass:[TSAttachmentStream class]]) {
        OWSLogError(@"Unexpected type for attachment builder: %@", attachment);
        return nil;
    }

    TSAttachmentStream *attachmentStream = (TSAttachmentStream *)attachment;
    return [attachmentStream buildProto];
}


- (DSKProtoAttachmentPointer *)buildProto
{
    DSKProtoAttachmentPointerBuilder *builder = [DSKProtoAttachmentPointer builder];

    builder.id = self.serverId;

    OWSAssertDebug(self.contentType.length > 0);
    builder.contentType = self.contentType;

    OWSLogVerbose(@"%@ Sending attachment with filename: '%@'", self.logTag, self.sourceFilename);
    builder.fileName = self.sourceFilename;

    builder.size = self.byteCount;
    builder.key = self.encryptionKey;
    builder.digest = self.digest;
    builder.flags = (self.isVoiceMessage ? DSKProtoAttachmentPointerFlagsVoiceMessage : 0)
        | (self.attachmentType == TSAttachmentTypeGif ? DSKProtoAttachmentPointerFlagsGif : 0);

    if (self.shouldHaveImageSize) {
        CGSize imageSize = self.imageSize;
        if (imageSize.width < NSIntegerMax && imageSize.height < NSIntegerMax) {
            NSInteger imageWidth = (NSInteger)round(imageSize.width);
            NSInteger imageHeight = (NSInteger)round(imageSize.height);
            if (imageWidth > 0 && imageHeight > 0) {
                builder.width = (UInt32)imageWidth;
                builder.height = (UInt32)imageHeight;
            }
        }
    }

    return [builder buildAndReturnError:nil];
}

#pragma mark - HOOK

- (void)willUpdateAttachment{
    self.appearInMediaGallery = [self attachmentIdShouldAppearInMediaGallery];
}

- (void)anyWillInsertWithTransaction:(SDSAnyWriteTransaction *)transaction {
    [super anyWillInsertWithTransaction:transaction];
    
    [self willUpdateAttachment];
}

- (void)anyWillUpdateWithTransaction:(SDSAnyWriteTransaction *)transaction {
    [super anyWillUpdateWithTransaction:transaction];
    
    [self willUpdateAttachment];
}

#pragma mark - utils

- (BOOL)attachmentIdShouldAppearInMediaGallery
{

    // Don't include nil or not yet downloaded attachments.
    if (![self isKindOfClass:[TSAttachmentStream class]]) {
        return NO;
    }
    
    return self.isImage || self.isVideo || self.isAnimated;
}

#pragma mark - Preprocessing

- (void)applyCompressedVideoPayloadWithRelativePath:(NSString *)relativeFilePath
                                          byteCount:(UInt32)byteCount
                                        contentType:(NSString *)contentType
                                              width:(UInt32)width
                                             height:(UInt32)height
{
    self.localRelativeFilePath = relativeFilePath;
    _byteCount = byteCount;
    _contentType = [contentType copy];

    // Keep sourceFilename's extension in sync with the new contentType
    // (e.g. IMG_xxxx.MOV → IMG_xxxx.mp4).
    if (_sourceFilename.length > 0) {
        NSString *newExtension = [MIMETypeUtil fileExtensionForMIMEType:contentType];
        if (newExtension.length > 0) {
            _sourceFilename =
                [[[_sourceFilename stringByDeletingPathExtension] stringByAppendingPathExtension:newExtension] copy];
        }
    }

    if (width > 0 && height > 0) {
        self.width = width;
        self.height = height;
    }

    @synchronized(self) {
        self.cachedImageWidth = nil;
        self.cachedImageHeight = nil;
    }
}

@end

NS_ASSUME_NONNULL_END
