//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "TSAttachment.h"

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, TSAttachmentPointerState) {
    TSAttachmentPointerStateEnqueued = 0,
    TSAttachmentPointerStateDownloading = 1,
    TSAttachmentPointerStateFailed = 2,
};

@class TSMessage;
@class DSKProtoAttachmentPointer;

//#ifdef DEBUG
//static NSInteger const kAttachmentAutoDownloadMaxSize = 190 * 1024;
//#else
static NSInteger const kAttachmentAutoDownloadMaxSize = 10 * 1024 * 1024;
//#endif

/**
 * A TSAttachmentPointer is a yet-to-be-downloaded attachment.
 */
@interface TSAttachmentPointer : TSAttachment

- (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                         albumId:(nullable NSString *)albumId
                  albumMessageId:(nullable NSString *)albumMessageId
            appearInMediaGallery:(BOOL)appearInMediaGallery
         attachmentSchemaVersion:(NSUInteger)attachmentSchemaVersion
                  attachmentType:(TSAttachmentType)attachmentType
                       byteCount:(unsigned int)byteCount
                     contentType:(NSString *)contentType
                   encryptionKey:(NSData *)encryptionKey
                    isDownloaded:(BOOL)isDownloaded
                        serverId:(unsigned long long)serverId
                  sourceFilename:(nullable NSString *)sourceFilename
                          digest:(nullable NSData *)digest
  mostRecentFailureLocalizedText:(nullable NSString *)mostRecentFailureLocalizedText
                           relay:(NSString *)relay
                           state:(TSAttachmentPointerState)state
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:albumId:albumMessageId:appearInMediaGallery:attachmentSchemaVersion:attachmentType:byteCount:contentType:encryptionKey:isDownloaded:serverId:sourceFilename:digest:mostRecentFailureLocalizedText:relay:state:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithServerId:(UInt64)serverId
                             key:(NSData *)key
                          digest:(nullable NSData *)digest
                       byteCount:(UInt32)byteCount
                     contentType:(NSString *)contentType
                           relay:(NSString *)relay
                  sourceFilename:(nullable NSString *)sourceFilename
                  attachmentType:(TSAttachmentType)attachmentType
                  albumMessageId:(nullable NSString *)albumMessageId
                         albumId:(nullable NSString *)albumId NS_DESIGNATED_INITIALIZER;


/// 构造 TSAttachmentPointer
/// - Parameters:
///   - attachmentProto: DSKProtoAttachmentPointer
///   - relay: relay
///   - albumMessageId: 附件所属消息 uniqueId (pin 消息｜头像不要传，其它附件必须传，用于历史过期附件清理)
///   - albumId: 附件所属会话 uniqueId (pin 消息｜头像不要传，其它附件必须传，用于历史过期附件清理)
+ (TSAttachmentPointer *)attachmentPointerFromProto:(DSKProtoAttachmentPointer *)attachmentProto
                                              relay:(nullable NSString *)relay
                                     albumMessageId:(nullable NSString *)albumMessageId
                                            albumId:(nullable NSString *)albumId;

/// 构造 TSAttachmentPointer 数组
/// - Parameters:
///   - attachmentProtos: DSKProtoAttachmentPointer
///   - relay: relay
///   - albumMessageId: 附件所属消息 uniqueId (pin 消息｜头像不要传，其它附件必须传，用于历史过期附件清理)
///   - albumId: 附件所属会话 uniqueId (pin 消息｜头像不要传，其它附件必须传，用于历史过期附件清理)
+ (NSArray<TSAttachmentPointer *> *)attachmentPointersFromProtos:(NSArray<DSKProtoAttachmentPointer *> *)attachmentProtos
                                                           relay:(nullable NSString *)relay
                                                  albumMessageId:(nullable NSString *)albumMessageId
                                                         albumId:(nullable NSString *)albumId;

@property (nonatomic, readonly) NSString *relay;
@property (atomic) TSAttachmentPointerState state;
@property (nullable, atomic) NSString *mostRecentFailureLocalizedText;

// Though now required, `digest` may be null for pre-existing records or from
// messages received from other clients
@property (nullable, nonatomic, readonly) NSData *digest;

- (void)updateAfterFileCheckWithServerId:(UInt64)serverId transaction:(SDSAnyWriteTransaction *)transaction;

@end

NS_ASSUME_NONNULL_END
