//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "DataSource.h"
#import "TSAttachment.h"

#if TARGET_OS_IPHONE
#import <UIKit/UIKit.h>

#endif

NS_ASSUME_NONNULL_BEGIN

@class DSKProtoAttachmentPointer;
@class TSAttachmentPointer;
@class SDSAnyWriteTransaction;
@class AVAsset;

FOUNDATION_EXPORT NSErrorDomain const TSAttachmentStreamErrorDomain;

typedef NS_ERROR_ENUM(TSAttachmentStreamErrorDomain, TSAttachmentStreamErrorCode) {
    /// A ciphertext file exists, but this model instance does not have the
    /// committed key/digest required to authenticate and decrypt it.
    TSAttachmentStreamErrorMissingEncryptionMetadata = 1,
};

@interface TSAttachmentStream : TSAttachment

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                         albumId:(nullable NSString *)albumId
                  albumMessageId:(nullable NSString *)albumMessageId
            appearInMediaGallery:(BOOL)appearInMediaGallery
         attachmentSchemaVersion:(NSUInteger)attachmentSchemaVersion
                  attachmentType:(TSAttachmentType)attachmentType
                       byteCount:(unsigned long long)byteCount
                     contentType:(NSString *)contentType
                   encryptionKey:(NSData *)encryptionKey
                          height:(unsigned int)height
                    isDownloaded:(BOOL)isDownloaded
               preprocessingKind:(TSAttachmentPreprocessingKind)preprocessingKind
             preprocessingParams:(nullable NSData *)preprocessingParams
                        serverId:(unsigned long long)serverId
                  sourceFilename:(nullable NSString *)sourceFilename
                           width:(unsigned int)width
      cachedAudioDurationSeconds:(nullable NSNumber *)cachedAudioDurationSeconds
               cachedImageHeight:(nullable NSNumber *)cachedImageHeight
                cachedImageWidth:(nullable NSNumber *)cachedImageWidth
               creationTimestamp:(NSDate *)creationTimestamp
                  decibelSamples:(nullable NSArray<NSNumber *> *)decibelSamples
                          digest:(nullable NSData *)digest
             encryptedDatalength:(NSInteger)encryptedDatalength
                      isUploaded:(BOOL)isUploaded
           lazyRestoreFragmentId:(nullable NSString *)lazyRestoreFragmentId
           localRelativeFilePath:(nullable NSString *)localRelativeFilePath
              serverAttachmentId:(NSString *)serverAttachmentId
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:albumId:albumMessageId:appearInMediaGallery:attachmentSchemaVersion:attachmentType:byteCount:contentType:encryptionKey:height:isDownloaded:preprocessingKind:preprocessingParams:serverId:sourceFilename:width:cachedAudioDurationSeconds:cachedImageHeight:cachedImageWidth:creationTimestamp:decibelSamples:digest:encryptedDatalength:isUploaded:lazyRestoreFragmentId:localRelativeFilePath:serverAttachmentId:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)init NS_UNAVAILABLE;
- (instancetype)initWithContentType:(NSString *)contentType
                          byteCount:(UInt64)byteCount
                     sourceFilename:(nullable NSString *)sourceFilename
                     albumMessageId:(nullable NSString *)albumMessageId
                            albumId:(nullable NSString *)albumId NS_DESIGNATED_INITIALIZER;

- (instancetype)initWithPointer:(TSAttachmentPointer *)pointer albumMessageId:(nullable NSString *)albumMessageId albumId:(nullable NSString *)albumId NS_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;

// Though now required, `digest` may be null for pre-existing records or from
// messages received from other clients
@property (nullable, nonatomic) NSData *digest;
@property (nonatomic, assign) NSInteger encryptedDatalength;

// This only applies for attachments being uploaded.
@property (atomic) BOOL isUploaded;

//record for report to server;
@property (atomic, copy) NSString *serverAttachmentId;

@property (nonatomic, readonly) NSDate *creationTimestamp;

@property (nullable, atomic, strong) NSArray<NSNumber *> *decibelSamples;
@property (nullable, atomic) NSNumber *cachedAudioDurationSeconds;

#if TARGET_OS_IPHONE
- (nullable UIImage *)image;
- (nullable UIImage *)thumbnailImage;
- (nullable NSData *)thumbnailData;
- (nullable NSData *)validStillImageData;
/// Generates a video still asynchronously; completion runs on an unspecified queue.
- (void)videoStillImageWithMaxSize:(CGSize)maxSize
                        completion:(void (^)(UIImage *_Nullable image))completion;
/// Writes the 512pt thumbnail if absent. Idempotent, but synchronous and slow for
/// video (hardware decode) — call off the main thread and outside a write transaction.
- (void)ensureThumbnail;
#endif

- (BOOL)isAnimated;
- (BOOL)isImage;
- (BOOL)isVideo;
- (BOOL)isAudio;
// TODO: rename to originalMediaURL 避免歧义
- (nullable NSURL *)mediaURL;

+ (BOOL)hasThumbnailForMimeType:(NSString *)contentType;

// TODO: rename to originalFilePath 避免歧义
- (nullable NSString *)filePath;
- (nullable NSString *)encryptedFilePath;
- (nullable NSString *)thumbnailPath;

/// Whether the canonical ciphertext file exists.
@property (nonatomic, readonly) BOOL hasEncryptedFile;
/// Whether this instance has a complete key and digest.
@property (nonatomic, readonly) BOOL hasUsableEncryptionMetadata;
/// Whether ciphertext exists and can be decrypted by this instance.
@property (nonatomic, readonly) BOOL isStoredEncrypted;

- (nullable NSData *)readDataFromFileWithError:(NSError **)error;
/// Convenience wrapper for UI consumers. Returns nil on authentication/decryption failure.
- (nullable NSData *)decryptedData;
- (BOOL)writeData:(NSData *)data error:(NSError **)error;
- (nullable NSData *)readEncryptedDataFromFileWithError:(NSError **)error;
- (BOOL)writeEncryptedData:(NSData *)data error:(NSError **)error;
- (BOOL)removeEncryptedDataWithError:(NSError **)error;
- (void)removeVoicePlaintextFile;
/// Removes the plaintext payload and derived thumbnail.
- (BOOL)removePlaintextFileWithError:(NSError **)error;
- (void)removePlaintextFile;
- (BOOL)writeDataSource:(id <DataSource>)dataSource;

/// A seekable, memory-backed AVAsset for encrypted-at-rest audio/video.
- (nullable AVAsset *)decryptedMediaAsset;

- (BOOL)isOversizeText;
- (nullable NSString *)readOversizeText;

+ (void)deleteAttachments;
+ (NSString *)attachmentsFolder;

- (BOOL)shouldHaveImageSize;
- (CGSize)imageSize;

- (CGFloat)audioDurationSeconds;
- (CGFloat)calculateAudioDurationSeconds;

+ (nullable NSError *)migrateToSharedData;

#pragma mark - Image Validation

- (BOOL)isValidImage;

#pragma mark - Update With... Methods

// Marks attachment as having completed "lazy backup restore."
- (void)updateWithLazyRestoreComplete;

- (nullable TSAttachmentStream *)cloneAsThumbnail;

/// Inserts a display-ready thumbnail without generating another derivative.
- (void)anyInsertPreparedThumbnailWithTransaction:(SDSAnyWriteTransaction *)transaction;

#pragma mark - Preprocessing

/// Apply the result of video compression preprocessing.
///
/// Updates the file path, byte count, content type, and (when non-zero) the
/// cached display dimensions. Also rewrites `sourceFilename`'s extension to
/// match the new contentType, so receivers picking a handler by filename
/// extension don't get an `IMG_xxxx.MOV` name advertising `video/mp4` bytes.
///
/// Does NOT touch upload state (`isUploaded`, `serverId`, ...) or the
/// preprocessing fields — those are the caller's responsibility.
- (void)applyCompressedVideoPayloadWithRelativePath:(NSString *)relativeFilePath
                                          byteCount:(UInt32)byteCount
                                        contentType:(NSString *)contentType
                                              width:(UInt32)width
                                             height:(UInt32)height
    NS_SWIFT_NAME(applyCompressedVideoPayload(relativePath:byteCount:contentType:width:height:));

#pragma mark - Protobuf

+ (nullable DSKProtoAttachmentPointer *)buildProtoForAttachmentId:(nullable NSString *)attachmentId;

- (DSKProtoAttachmentPointer *)buildProto;

@end

NS_ASSUME_NONNULL_END
