//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "BaseModel.h"
#import "TSConstants.h"
#import "DTReadPositionEntity.h"
#import "TSMessageMacro.h"

NS_ASSUME_NONNULL_BEGIN

@class TSThread;
@class SDSAnyReadTransaction;

@interface OWSLinkedDeviceReadReceipt : BaseModel

@property (nonatomic, readonly) NSString *senderId;
@property (nonatomic, readonly) uint64_t messageIdTimestamp;
@property (nonatomic, readonly) uint64_t readTimestamp;
@property (nonatomic, assign) TSWhisperMessageType whisperMessageType;
@property (nonatomic, assign) BOOL isLargeGroupThread;

@property (nonatomic, strong) DTReadPositionEntity *readPosition;

@property (nonatomic, copy) NSString *associatedUniqueThreadId;

@property (nonatomic, assign) TSMessageModeType messageModeType;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
        associatedUniqueThreadId:(NSString *)associatedUniqueThreadId
              isLargeGroupThread:(BOOL)isLargeGroupThread
              messageIdTimestamp:(uint64_t)messageIdTimestamp
                 messageModeType:(TSMessageModeType)messageModeType
                    readPosition:(DTReadPositionEntity *)readPosition
                   readTimestamp:(uint64_t)readTimestamp
                        senderId:(NSString *)senderId
              whisperMessageType:(TSWhisperMessageType)whisperMessageType
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:associatedUniqueThreadId:isLargeGroupThread:messageIdTimestamp:messageModeType:readPosition:readTimestamp:senderId:whisperMessageType:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithSenderId:(NSString *)senderId
              messageIdTimestamp:(uint64_t)messageIdtimestamp
                   readTimestamp:(uint64_t)readTimestamp;

+ (nullable OWSLinkedDeviceReadReceipt *)findLinkedDeviceReadReceiptWithSenderId:(NSString *)senderId
                                                              messageIdTimestamp:(uint64_t)messageIdTimestamp
                                                                     transaction:
                                                                         (SDSAnyReadTransaction *)transaction;

@end

NS_ASSUME_NONNULL_END
