//
//  TSMessageReadPosition.h
//  TTServiceKit
//
//  Created by Kris.s on 2022/11/4.
//

#import <TTServiceKit/TTServiceKit.h>

NS_ASSUME_NONNULL_BEGIN

@class DTReadPositionEntity;

@interface TSMessageReadPosition : BaseModel

@property (nonatomic, copy, readonly) NSString *uniqueThreadId;

@property (nonatomic, copy, readonly) NSString *recipientId;

@property (nonatomic, assign) uint64_t readAt;

@property (nonatomic, assign) uint64_t maxServerTime;

@property (nonatomic, assign) uint64_t maxNotifySequenceId;

@property (nonatomic, assign) uint64_t creationTimestamp;

@property (nonatomic, assign) uint64_t updateCount;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
               creationTimestamp:(uint64_t)creationTimestamp
             maxNotifySequenceId:(uint64_t)maxNotifySequenceId
                   maxServerTime:(uint64_t)maxServerTime
                          readAt:(uint64_t)readAt
                     recipientId:(NSString *)recipientId
                  uniqueThreadId:(NSString *)uniqueThreadId
                     updateCount:(uint64_t)updateCount
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:creationTimestamp:maxNotifySequenceId:maxServerTime:readAt:recipientId:uniqueThreadId:updateCount:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithUniqueThreadId:(NSString *)uniqueThreadId
                     recipientId:(NSString *)recipientId
                    readPosition:(DTReadPositionEntity *)readPosition;

+ (NSString *)generateUniqueIdWithUniqueThreadId:(NSString *)uniqueThreadId
                                     recipientId:(NSString *)recipientId
                                       timestamp:(uint64_t)timestamp;

+ (NSString *)generateUniqueIdWithUniqueThreadId:(NSString *)uniqueThreadId
                                     recipientId:(NSString *)recipientId;

- (void)updateOrInsertWithTransaction:(SDSAnyWriteTransaction *)transaction;

@end

NS_ASSUME_NONNULL_END
