//
//  SignalAccountSecondary.h
//  TTServiceKit
//
//  Created by Kris.s on 2022/11/3.
//

#import "BaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@interface SignalAccountSecondary : BaseModel

@property (nonatomic, copy, readonly) NSString *fullName;
@property (nonatomic, copy, readonly) NSString *email;
@property (nonatomic, copy, readonly) NSString *signature;
@property (nonatomic, copy, readonly) NSString *buName;
@property (nonatomic, copy, readonly) NSString *remarkName;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                          buName:(NSString *)buName
                           email:(NSString *)email
                        fullName:(NSString *)fullName
                      remarkName:(NSString *)remarkName
                       signature:(NSString *)signature
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:buName:email:fullName:remarkName:signature:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithUniqueId:(NSString *)uniqueId
                        fullName:(NSString *)fullName
                           email:(NSString *)email
                      remarkName:(NSString *)remarkName
                       signature:(NSString *)signature
                          buName:(NSString *)buName;

@end

NS_ASSUME_NONNULL_END
