//
//  TSGroupThreadSecondary.h
//  TTServiceKit
//
//  Created by Kris.s on 2022/11/3.
//

#import "BaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@interface TSGroupThreadSecondary : BaseModel

@property (nonatomic, copy, readonly) NSString *lastMessageDate;
@property (nonatomic, copy, readonly) NSString *members;
@property (nonatomic, copy, readonly) NSString *groupName;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                       groupName:(NSString *)groupName
                 lastMessageDate:(NSString *)lastMessageDate
                         members:(NSString *)members
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:groupName:lastMessageDate:members:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithUniqueId:(NSString *)uniqueId
                 lastMessageDate:(NSString *)lastMessageDate
                         members:(NSString *)members
                       groupName:(NSString *)groupName;
@end

NS_ASSUME_NONNULL_END
