//
//  TSMessageSecondary.h
//  TTServiceKit
//
//  Created by Kris.s on 2022/11/3.
//

#import "BaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@interface TSMessageSecondary : BaseModel

@property (nonatomic, copy, readonly) NSString *message;
@property (nonatomic, copy, readonly) NSString *thread;
@property (nonatomic, copy, readonly) NSString *timestamp;
@property (nonatomic, assign, readonly) BOOL display;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                         display:(BOOL)display
                         message:(NSString *)message
                          thread:(NSString *)thread
                       timestamp:(NSString *)timestamp
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:display:message:thread:timestamp:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithUniqueId:(NSString *)uniqueId
                         message:(NSString *)message
                         thread:(NSString *)thread
                      timestamp:(NSString *)timestamp
                        display:(BOOL)display;


@end

NS_ASSUME_NONNULL_END
