//
//  DTGroupNotifyEntity.m
//  TTServiceKit
//
//  Created by Kris.s on 2021/9/26.
//

#import "DTGroupNotifyEntity.h"

@implementation DTGroupRemindNotifyEntity

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
    return [NSDictionary mtl_identityPropertyMapWithModel:[self class]];;
}

@end

@implementation DTGroupBaseInfoNotifyEntity

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                    anyoneRemove:(BOOL)anyoneRemove
                          avatar:(NSString *)avatar
                             ext:(BOOL)ext
                             gid:(NSString *)gid
                  invitationRule:(nullable NSNumber *)invitationRule
              messageClearAnchor:(unsigned long long)messageClearAnchor
                   messageExpiry:(nullable NSNumber *)messageExpiry
                            name:(NSString *)name
                     publishRule:(nullable NSNumber *)publishRule
                          rejoin:(BOOL)rejoin
                     remindCycle:(NSString *)remindCycle
                          action:(DTGroupNotifyAction)action
{
    self = [super initWithGrdbId:grdbId
                        uniqueId:uniqueId
                      anyoneRemove:anyoneRemove
                            avatar:avatar
                               ext:ext
                               gid:gid
                    invitationRule:invitationRule
                messageClearAnchor:messageClearAnchor
                     messageExpiry:messageExpiry
                              name:name
                       publishRule:publishRule
                            rejoin:rejoin
                       remindCycle:remindCycle];

    if (!self) {
        return self;
    }

    _action = action;

    return self;
}

// clang-format on

// --- CODE GENERATION MARKER

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
    return [NSDictionary mtl_identityPropertyMapWithModel:[self class]];;
}

@end

@implementation DTGroupAnnouncementNotifyEntity

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
    NSMutableDictionary *map = [NSDictionary mtl_identityPropertyMapWithModel:[self class]].mutableCopy;
    map[@"aId"] = @"id";
    return map.copy;
}

@end

@implementation DTPinnedMessageNotifyEntity

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    
    NSMutableDictionary *map = [NSDictionary mtl_identityPropertyMapWithModel:[self class]].mutableCopy;
    map[@"pinId"] = @"id";
    
    return map.copy;
}

@end

@implementation DTGroupMemberNotifyEntity

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
    return [NSDictionary mtl_identityPropertyMapWithModel:[self class]];;
}

@end

@implementation DTGroupNotifyEntity

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
    NSMutableDictionary *map = [NSDictionary mtl_identityPropertyMapWithModel:[self class]].mutableCopy;
    map[@"source"] = @"operator";
    map[@"sourceDeviceId"] = @"operatorDeviceId";
    return map.copy;
}

+ (NSValueTransformer *)groupJSONTransformer {
    return [MTLJSONAdapter dictionaryTransformerWithModelClass:[DTGroupBaseInfoNotifyEntity class]];
}

+ (NSValueTransformer *)membersJSONTransformer {
    return [MTLJSONAdapter arrayTransformerWithModelClass:[DTGroupMemberNotifyEntity class]];
}

+ (NSValueTransformer *)groupAnnouncementsJSONTransformer {
    return [MTLJSONAdapter arrayTransformerWithModelClass:[DTGroupAnnouncementNotifyEntity class]];
}

+ (NSValueTransformer *)groupPinsJSONTransformer {
    return [MTLJSONAdapter arrayTransformerWithModelClass:[DTPinnedMessageNotifyEntity class]];
}

+ (NSValueTransformer *)groupRemindJSONTransformer {
    return [MTLJSONAdapter dictionaryTransformerWithModelClass:[DTGroupRemindNotifyEntity class]];
}

// create: 会议创建提醒，remind: 会议开始前 n 分钟提醒
+ (NSValueTransformer *)typeJSONTransformer {
    return [NSValueTransformer mtl_valueMappingTransformerWithDictionary:@{
        @"create": @(DTMeetingReminderTypeCreate),
        @"remind": @(DTMeetingReminderTypeRemind),
        @"cancel": @(DTMeetingReminderTypeCancel),
    }];
}

@end
