//
//  DTGroupBaseInfoEntity.h
//  TTServiceKit
//
//  Created by Kris.s on 2021/9/26.
//

#import <Mantle/Mantle.h>
#import "BaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@interface DTGroupBaseInfoEntity : BaseModel<MTLJSONSerializing>

@property (nonatomic, copy) NSString *gid;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, nullable) NSNumber *messageExpiry;
@property (nonatomic, copy) NSString *avatar;
@property (nonatomic, nullable) NSNumber *invitationRule; // 2:全员允许, 1:管理员和群主, 0:群主
@property (nonatomic, copy) NSString *remindCycle;
@property (nonatomic, assign) BOOL anyoneRemove;
@property (nonatomic, assign) BOOL rejoin;
@property (nonatomic, strong, nullable) NSNumber *publishRule;
@property (nonatomic, assign) BOOL ext;
@property (nonatomic, assign) UInt64 messageClearAnchor;

///不需要入库字段
/// 需要在{Project}/Scripts/sds_codegen/sds_config/sds-config.json 文件中进行忽略
///===========
@property (nonatomic, assign) BOOL anyoneChangeName;
@property (nonatomic, assign) BOOL anyoneChangeAutoClear;
@property (nonatomic, assign) BOOL autoClear;
@property (nonatomic, assign) BOOL privilegeConfidential;
@property (nonatomic, assign) BOOL archive;
@property (nonatomic, assign) BOOL privateChat;
///===========

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                    anyoneRemove:(BOOL)anyoneRemove
                          avatar:(NSString *)avatar
                             ext:(BOOL)ext
                             gid:(NSString *)gid
                  invitationRule:(nullable NSNumber *)invitationRule
              messageClearAnchor:(unsigned long long)messageClearAnchor
                   messageExpiry:(nullable NSNumber *)messageExpiry
                            name:(NSString *)name
                     publishRule:(nullable NSNumber *)publishRule
                          rejoin:(BOOL)rejoin
                     remindCycle:(NSString *)remindCycle
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:anyoneRemove:avatar:ext:gid:invitationRule:messageClearAnchor:messageExpiry:name:publishRule:rejoin:remindCycle:));

// clang-format on

// --- CODE GENERATION MARKER

@end

NS_ASSUME_NONNULL_END
