//
//  DTGroupNotifyEntity.h
//  TTServiceKit
//
//  Created by Kris.s on 2021/9/26.
//

#import <UIKit/UIKit.h>
#import <Mantle/Mantle.h>
#import "DTGroupMemberEntity.h"
#import "DTGroupBaseInfoEntity.h"
#import "DTGroupAnnouncementEntity.h"
#import "DTPinnedMessageEntity.h"

NS_ASSUME_NONNULL_BEGIN
/*
 {
     "gid":"d21e9eb2bb534ad689ecde31f57baf0c",
     "ver":1,
     "groupNotifyType":0,
     "groupVersion":1,
     "group":{
       "name":"Johny",
       "messageExpiry":600,
       "avatar":"adfadf",
       "action":0,
       "invitationRule":2
     },
     "members":[
       {
         "uid":"+72212204429",
         "role":0,
         "displayName":"",
         "notification":1,
         "action":0
       },
       {
         "uid":"+79230788022",
         "role":2,
         "displayName":"",
         "notification":1,
         "action":0
       }
     ],
     "groupAnnouncements":null
   }
 */

/*
 {
         "id":"cdfbc6b7d6b847909d161cfba633582d",
         "announcementExpiry":0,
         "content":null,
         "reviseTime":0,
         "action":3
       }
 */

typedef NS_ENUM(NSUInteger, DTGroupNotifyAction) {
    DTGroupNotifyActionAdd,
    DTGroupNotifyActionUpdate,
    DTGroupNotifyActionLeave,
    DTGroupNotifyActionDelete
};

typedef NS_ENUM(NSUInteger, DTGroupNotifyType) {
    DTGroupNotifyTypeBase = 0,                      //0:基础信息变更（创建，解散及群基础信息）
    DTGroupNotifyTypeMemberChanged,                 //1:成员信息变更（成员增删）
    DTGroupNotifyTypeMemberInfo,                    //2:人员基本信息变更（群成员的基础信息，角色变更）
    DTGroupNotifyTypeAnnouncement,                  //3:公告变更（新增、变更）
    DTGroupNotifyTypePersonalConfig,                //4:个人配置变更
    DTGroupNotifyTypePinUpdate,                     //5:pin消息变更
    DTGroupNotifyTypeCallEndFeedback,               //6:通话结束反馈
    DTGroupNotifyTypeMeeting_MemberJoinOrLeft,      //7:会议人员加入/离开
    DTGroupNotifyTypeGroupCycleReminder,            //8:群周期提醒
    DTGroupNotifyTypeMeetingReminder,               //9:会议提醒
    
    DTGroupNotifyTypeGroupRapidRole = 100           //100:RAPID标签更改(迭代版本后需要移出)
};

typedef NS_ENUM(NSInteger, DTGroupNotifyDetailType) {
    DTGroupNotifyDetailTypeCreateGroup = 0,
    DTGroupNotifyDetailTypeJoinGroup,
    DTGroupNotifyDetailTypeLeaveGroup, // 用户主动退出群，会附带被踢出成员列表
    DTGroupNotifyDetailTypeInviteJoinGroup,
    DTGroupNotifyDetailTypeKickoutGroup,    //有成员被踢出群，会附带被踢出成员列表
    DTGroupNotifyDetailTypeDismissGroup = 5, //用户解散群租
    
    DTGroupNotifyDetailTypeGroupNameChange,
    DTGroupNotifyDetailTypeGroupAvatarChange,
    DTGroupNotifyDetailTypeGroupMsgExpiryChange = 8,
    
    DTGroupNotifyDetailTypeGroupAddAdmin,
    DTGroupNotifyDetailTypeGroupDeleteAdmin,
    DTGroupNotifyDetailTypeGroupMemberInfoChange,//
    DTGroupNotifyDetailTypeGroupOwnerChange = 12,
    
    DTGroupNotifyDetailTypeGroupAddAnnnouncement,
    DTGroupNotifyDetailTypeGroupUpdateAnnnouncement,
    DTGroupNotifyDetailTypeGroupDeleteAnnnouncement = 15,
    
    DTGroupNotifyDetailTypeGroupOtherChange,
    DTGroupNotifyDetailTypeGroupSelfInfoChange,
    DTGroupNotifyDetailTypeGroupAddPin,
    DTGroupNotifyDetailTypeGroupDeletePin,
    DTGroupNotifyDetailTypeGroupInvitationRuleChange,
    DTGroupNotifyDetailTypeGroupRemindChange,//修改
    DTGroupNotifyDetailTypeGroupRemind,//群周期提醒
    DTGroupNotifyDetailTypeGroupRapidRoleChange,
    DTGroupNotifyDetailTypeGroupAnyoneRemoveChange,
    DTGroupNotifyDetailTypeGroupRejoinChange,
    DTGroupNotifyDetailTypeGroupExtChange,
    DTGroupNotifyDetailTypeGroupPublishRuleChange = 27,
    DTGroupNotifyDetailTypeGroupInactive = 28,
    DTGroupNotifyDetailTypeGroupLinkJoin = 29,
    DTGroupNotifyDetailTypeGroupMaxSizeChange = 30,
    DTGroupNotifyDetailTypeGroupAnyoneChangeNameChange = 31,
    DTGroupNotifyDetailTypeAnyoneChangeAutoClearChange = 32,
    DTGroupNotifyDetailTypeAutoClearChange = 33,
    DTGroupNotifyDetailTypeKickoutAutoClear = 34, //
    DTGroupNotifyDetailTypeDestroy = 35, // chative 60天不活跃服务端解散群
    DTGroupNotifyDetailTypePrivilegeConfidential = 36,
    DTGroupNotifyDetailTypeWeblinkInviteJoin = 37, // chative
    DTGroupNotifyDetailTypeWeblinkInviteSwitchChange = 38, // chative
    DTGroupNotifyDetailTypeArchive = 39, // 群解散归档 （已废弃）
    DTGroupNotifyDetailTypeGroupCostChange = 40,
    DTGroupNotifyDetailTypePrivateChatChange = 41,
    DTGroupNotifyDetailTypeGroupAccountInvalid = 999
};

@interface DTGroupRemindNotifyEntity : MTLModel<MTLJSONSerializing>

@property (nonatomic, copy) NSString *remindCycle;

@end

@interface DTGroupBaseInfoNotifyEntity : DTGroupBaseInfoEntity

@property (nonatomic, assign) DTGroupNotifyAction action;

@property (nonatomic, assign) uint64_t messageClearAnchor;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                    anyoneRemove:(BOOL)anyoneRemove
                          avatar:(NSString *)avatar
                             ext:(BOOL)ext
                             gid:(NSString *)gid
                  invitationRule:(nullable NSNumber *)invitationRule
              messageClearAnchor:(unsigned long long)messageClearAnchor
                   messageExpiry:(nullable NSNumber *)messageExpiry
                            name:(NSString *)name
                     publishRule:(nullable NSNumber *)publishRule
                          rejoin:(BOOL)rejoin
                     remindCycle:(NSString *)remindCycle
                          action:(DTGroupNotifyAction)action
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:anyoneRemove:avatar:ext:gid:invitationRule:messageClearAnchor:messageExpiry:name:publishRule:rejoin:remindCycle:action:));

// clang-format on

// --- CODE GENERATION MARKER

@end


@interface DTGroupAnnouncementNotifyEntity : DTGroupAnnouncementEntity

@property (nonatomic, assign) DTGroupNotifyAction action;

@end

@interface DTPinnedMessageNotifyEntity : DTPinnedMessageEntity

@property (nonatomic, assign) DTGroupNotifyAction action;

@end

@interface DTGroupMemberNotifyEntity : DTGroupMemberEntity

@property (nonatomic, assign) DTGroupNotifyAction action;
@property (nonatomic, copy) NSString *inviteCode;

@end


typedef NS_ENUM(NSInteger, DTMeetingReminderType) {
    DTMeetingReminderTypeUnknow = 0,
    DTMeetingReminderTypeCreate,
    DTMeetingReminderTypeRemind,
    DTMeetingReminderTypeCancel
};

@interface DTGroupNotifyEntity : MTLModel<MTLJSONSerializing>

@property (nonatomic, copy) NSString *gid;
@property (nonatomic, assign) DTGroupNotifyType groupNotifyType;
@property (nonatomic, assign) DTGroupNotifyDetailType groupNotifyDetailedType;
@property (nonatomic, assign) NSInteger groupVersion;
@property (nonatomic, copy) NSString *source;
@property (nonatomic, assign) NSInteger sourceDeviceId;
@property (nonatomic, strong, nullable) DTGroupBaseInfoNotifyEntity *group;
@property (nonatomic, strong) NSArray<DTGroupMemberNotifyEntity *> *members;
@property (nonatomic, strong) NSArray<DTGroupAnnouncementNotifyEntity *> *groupAnnouncements;
@property (nonatomic, strong) NSArray<DTPinnedMessageNotifyEntity *> *groupPins;
// "join" "leave"
@property (nonatomic, copy) NSString *event;
// uid of the member who join/left the meeting
@property (nonatomic, copy) NSString *uid;
@property (nonatomic, assign) NSTimeInterval timestamp;
@property (nonatomic, strong) DTGroupRemindNotifyEntity *groupRemind;

/// Group meeting duration
@property (nonatomic, assign) NSUInteger duration;

// create: 会议创建提醒，remind: 会议开始前 n 分钟提醒
@property (nonatomic, assign) DTMeetingReminderType type;
// e.g. 5 minutes/1 hour
@property (nonatomic, copy) NSString *reminder;
// 预约会议的人
@property (nonatomic, copy) NSString *organizer;
@property (nonatomic, copy) NSString *startAt;
@property (nonatomic, copy) NSString *meetingName;
@property (nonatomic, copy) NSString *link;
@property (nonatomic, assign) BOOL isRecurrence;
@property (nonatomic, copy) NSString *meetingId;
@end

NS_ASSUME_NONNULL_END
