//
//  OWSMessageContentJob.m
//  TTServiceKit
//
//  Created by Kris.s on 2022/10/20.
//

#import "OWSMessageContentJob.h"
#import <TTServiceKit/TTServiceKit-Swift.h>

#pragma mark -

@implementation OWSMessageContentJob

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                       createdAt:(NSDate *)createdAt
                    envelopeData:(NSData *)envelopeData
            lastestHandleVersion:(NSString *)lastestHandleVersion
                   plaintextData:(nullable NSData *)plaintextData
                 unsupportedFlag:(BOOL)unsupportedFlag
{
    self = [super initWithGrdbId:grdbId
                        uniqueId:uniqueId];

    if (!self) {
        return self;
    }

    _createdAt = createdAt;
    _envelopeData = envelopeData;
    _lastestHandleVersion = lastestHandleVersion;
    _plaintextData = plaintextData;
    _unsupportedFlag = unsupportedFlag;

    return self;
}

// clang-format on

// --- CODE GENERATION MARKER

+ (NSString *)collection
{
    return @"OWSBatchMessageProcessingJob";
}

- (instancetype)initWithEnvelopeData:(NSData *)envelopeData plaintextData:(NSData *_Nullable)plaintextData
{
    OWSAssertDebug(envelopeData);

    self = [super initWithUniqueId:[NSUUID new].UUIDString];
    if (!self) {
        return self;
    }

    _envelopeData = envelopeData;
    _plaintextData = plaintextData;
    _createdAt = [NSDate new];

    return self;
}

- (nullable instancetype)initWithCoder:(NSCoder *)coder
{
    return [super initWithCoder:coder];
}

- (nullable DSKProtoEnvelope *)envelopeProto
{
    NSError *error;
    DSKProtoEnvelope *envelope = [[DSKProtoEnvelope alloc] initWithSerializedData:self.envelopeData error:&error];
    
    if (error) {
        OWSLogError(@"%@ error:%@.", self.logTag, error);
    }
    
    return envelope;
}

@end
