//
//  OWSMessageContentJob.h
//  TTServiceKit
//
//  Created by Kris.s on 2022/10/20.
//

#import "BaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@class DSKProtoEnvelope;
@class SDSAnyReadTransaction;

#pragma mark - Persisted data model

@interface OWSMessageContentJob : BaseModel

@property (nonatomic, readonly) NSDate *createdAt;
@property (nonatomic, readonly) NSData *envelopeData;
@property (nonatomic, readonly, nullable) NSData *plaintextData;
@property (nonatomic, assign) BOOL unsupportedFlag;
@property (nonatomic, copy) NSString *lastestHandleVersion;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                       createdAt:(NSDate *)createdAt
                    envelopeData:(NSData *)envelopeData
            lastestHandleVersion:(NSString *)lastestHandleVersion
                   plaintextData:(nullable NSData *)plaintextData
                 unsupportedFlag:(BOOL)unsupportedFlag
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:createdAt:envelopeData:lastestHandleVersion:plaintextData:unsupportedFlag:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithEnvelopeData:(NSData *)envelopeData
                       plaintextData:(NSData *_Nullable)plaintextData NS_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;
- (instancetype)initWithUniqueId:(NSString *_Nullable)uniqueId NS_UNAVAILABLE;
- (nullable DSKProtoEnvelope *)envelopeProto;

@end
NS_ASSUME_NONNULL_END
