name: build_tt

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop
      - 'release/**'

jobs:
  build:
    name: Compile Verification
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          bundle install
          bundle exec pod install

      - name: Build
        env:
          FASTLANE_SKIP_UPDATE_CHECK: 1
        run: |
          bundle exec fastlane ios build \
            configuration:Debug \
            --env build_tt \
            --verbose