//
//  DTCardMessageEntity.h
//  TTServiceKit
//
//  Created by Kris.s on 2022/5/18.
//

#import "BaseModel.h"
#import <Mantle/Mantle.h>

NS_ASSUME_NONNULL_BEGIN

@class DSKProtoCard;
@class SDSAnyWriteTransaction;

typedef NS_ENUM(NSInteger, DTReceivedCardType) {
    DTReceivedCardTypeIncoming = 0,
    DTReceivedCardTypeSync,
    DTReceivedCardTypeRefresh,
    DTReceivedCardTypePin,
    DTReceivedCardTypePinRefreshed,
    DTReceivedCardTypeMeeting
};

@interface DTCardMessageEntity : BaseModel<MTLJSONSerializing>

//required
@property (nonatomic, copy) NSString *appId;
@property (nonatomic, copy) NSString *cardId;
@property (nonatomic, assign) uint32_t version;
@property (nonatomic, copy) NSString *content;
//optional
@property (nonatomic, copy, nullable) NSString *creator;
@property (nonatomic, assign) uint64_t timestamp;
@property (nonatomic, assign) uint32_t contentType;
@property (nonatomic, assign) uint32_t cardType;
@property (nonatomic, assign) BOOL fixedWidth;

//
@property (nonatomic, copy) NSAttributedString *attributeContent;
@property (nonatomic, copy) NSString *markdownVersion;

@property (nonatomic, copy) NSString *source;
@property (nonatomic, copy) NSString *conversationId;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                           appId:(NSString *)appId
                          cardId:(NSString *)cardId
                         content:(NSString *)content
                     contentType:(unsigned int)contentType
                         creator:(nullable NSString *)creator
                      fixedWidth:(BOOL)fixedWidth
                       timestamp:(uint64_t)timestamp
                         version:(unsigned int)version
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:appId:cardId:content:contentType:creator:fixedWidth:timestamp:version:));

// clang-format on

// --- CODE GENERATION MARKER

+ (DTCardMessageEntity *)cardEntityWithProto:(DSKProtoCard *)cardProto;
+ (nullable DSKProtoCard *)cardProtoWithEntity:(DTCardMessageEntity *)cardEntity;

- (NSString *)generateUniqueIdWithSource:(NSString *)source conversationId:(NSString *)conversationId;

- (void)updateDataWithCardUniqueId:(NSString *)cardUniqueId
                  receivedCardType:(DTReceivedCardType)receivedCardType
                       transaction:(SDSAnyWriteTransaction *)transaction
                      updateAction:(nullable void(^)(void))updateAction;

@end

NS_ASSUME_NONNULL_END
