//
//  DTPinnedMessage.h
//  Wea
//
//  Created by Ethan on 2022/3/19.
//

#import "TSMessage.h"
#import "DTRealSourceEntity.h"

@class TSOutgoingMessage;
@class TSIncomingMessage;
@class DSKProtoEnvelopeBuilder;
@class DSKProtoDataMessageBuilder;
@class DSKProtoDataMessageQuoteBuilder;
@class DSKProtoDataMessageForwardContext;
@class DTPinnedMessageEntity;

NS_ASSUME_NONNULL_BEGIN

@interface DTPinnedMessage : BaseModel

@property (nonatomic, copy, nullable) NSString *pinId;
@property (nonatomic, copy) NSString *groupId;
@property (nonatomic, strong) DTRealSourceEntity *realSource;
@property (nonatomic, readonly) TSMessage *contentMessage;
@property (nonatomic, strong, nullable) TSOutgoingMessage *outgoingMessage;
@property (nonatomic, strong, nullable) TSIncomingMessage *incomingMessage;
@property (nonatomic, assign) uint64_t timestampForSorting;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                         groupId:(NSString *)groupId
                 incomingMessage:(nullable TSIncomingMessage *)incomingMessage
                 outgoingMessage:(nullable TSOutgoingMessage *)outgoingMessage
                           pinId:(nullable NSString *)pinId
                      realSource:(DTRealSourceEntity *)realSource
             timestampForSorting:(uint64_t)timestampForSorting
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:groupId:incomingMessage:outgoingMessage:pinId:realSource:timestampForSorting:));

// clang-format on

// --- CODE GENERATION MARKER

+ (DTPinnedMessage *)pinnedMessageFromMessage:(TSMessage *)message;

/// 原消息->NSData->base64
/// @param message 原消息
+ (NSString *)pinMessageEnvelopeBase64String:(TSMessage *)message;

/// base64->NSData->DTPinnedMessage(TSIncomingMessage/TSOutgoingMessage)
/// @param messageEntity with base64String and cardEntity
/// @param groupId groupId
/// @param transaction transaction
+ (DTPinnedMessage *)parseBase64StringToPinnedMessage:(DTPinnedMessageEntity*)messageEntity groupId:(NSString *)groupId transaction:(SDSAnyWriteTransaction *)transaction;

+ (DSKProtoEnvelopeBuilder *)envelopeBuilderWithMessage:(TSMessage *)message;

+ (DSKProtoDataMessageBuilder *)dataMessageBuilderWithMessage:(TSMessage *)message;

+ (nullable DSKProtoDataMessageQuoteBuilder *)quotedMessageBuilderWith:(TSQuotedMessage *)quoteMessage;

+ (nullable DSKProtoDataMessageForwardContext *)combinedForwardingContextProtoWith:(DTCombinedForwardingMessage *)combinedForwardingMessage;

- (void)downloadAllAttachmentWithTransaction:(SDSAnyWriteTransaction *)transaction
                                     success:(void(^ _Nullable)(TSAttachmentStream *attachmentStream))success
                                     failure:(void(^ _Nullable)(NSError *error))failure;

- (void)removePinMessageWithTransaction:(SDSAnyWriteTransaction *)transaction;

@end

NS_ASSUME_NONNULL_END
