//
//  DTReactionMessage.h
//  TTServiceKit
//
//  Created by Ethan on 2022/5/20.
//

#import <Mantle/Mantle.h>
#import "DTRealSourceEntity.h"
#import "BaseModel.h"

@class TSMessage;
@class DSKProtoDataMessage;
@class DSKProtoDataMessageReaction;

NS_ASSUME_NONNULL_BEGIN

@interface DTReactionMessage : BaseModel

@property (nonatomic, copy) NSString *emoji;
//被添加表情的原始消息的来源
@property (nonatomic, strong) DTRealSourceEntity *source;
@property (nonatomic, assign) BOOL removeAction;
@property (nonatomic, copy) NSString *originalUniqueId;

//MARK: 仅入库，消息通道不需要。当前reaction消息的来源
@property (nonatomic, strong) DTRealSourceEntity *ownSource;
@property (nonatomic, copy) NSString *conversationId;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                  conversationId:(NSString *)conversationId
                           emoji:(NSString *)emoji
                originalUniqueId:(NSString *)originalUniqueId
                       ownSource:(DTRealSourceEntity *)ownSource
                    removeAction:(BOOL)removeAction
                          source:(DTRealSourceEntity *)source
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:conversationId:emoji:originalUniqueId:ownSource:removeAction:source:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithEmoji:(NSString *)emoji
                source:(DTRealSourceEntity *)source
                       remove:(BOOL)remove;


+ (DTReactionMessage *)reactionWithProto:(DSKProtoDataMessage *)dataMessage;
+ (nullable DSKProtoDataMessageReaction *)reactionProtoWithReaction:(nullable DTReactionMessage *)reaction;

- (void)relateReactionMessageWithOriginMessage:(TSMessage *)origionMessage
                                   transaction:(SDSAnyWriteTransaction *)transaction;
+ (NSArray <DTReactionMessage *> *)findReactionMessagesWithMessage:(TSMessage *)message
                                                       transaction:(SDSAnyWriteTransaction *)transaction;

- (void)saveWithTransaction:(SDSAnyWriteTransaction *)transaction;

@end

@interface DTReactionSource : MTLModel

@property (nonatomic, copy) NSString *source;
@property (nonatomic, assign) uint64_t timestamp;
@property (nonatomic, assign, getter=isRemove) BOOL remove;

@end

NS_ASSUME_NONNULL_END
