//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "TSInfoMessage.h"

NS_ASSUME_NONNULL_BEGIN

@class OWSDisappearingMessagesConfiguration;
@class TSThread;

@interface OWSDisappearingConfigurationUpdateInfoMessage : TSInfoMessage

//@property (nonatomic, readonly) BOOL configurationIsEnabled;
@property (nonatomic, readonly) uint32_t configurationDurationSeconds;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
        associatedUniqueThreadId:(NSString *)associatedUniqueThreadId
                notifySequenceId:(uint64_t)notifySequenceId
             receivedAtTimestamp:(uint64_t)receivedAtTimestamp
                      sequenceId:(uint64_t)sequenceId
                 serverTimestamp:(uint64_t)serverTimestamp
                       timestamp:(uint64_t)timestamp
                  uniqueThreadId:(NSString *)uniqueThreadId
                       atPersons:(nullable NSString *)atPersons
                   attachmentIds:(NSArray<NSString *> *)attachmentIds
                            body:(nullable NSString *)body
                            card:(nullable DTCardMessageEntity *)card
                    cardUniqueId:(nullable NSString *)cardUniqueId
                     cardVersion:(unsigned int)cardVersion
       combinedForwardingMessage:(nullable DTCombinedForwardingMessage *)combinedForwardingMessage
                    contactShare:(nullable OWSContact *)contactShare
                        editable:(BOOL)editable
                   envelopSource:(nullable NSString *)envelopSource
                 expireStartedAt:(uint64_t)expireStartedAt
                       expiresAt:(uint64_t)expiresAt
                expiresInSeconds:(unsigned int)expiresInSeconds
                 isPinnedMessage:(BOOL)isPinnedMessage
                        mentions:(nullable NSArray<DTMention *> *)mentions
                 messageModeType:(TSMessageModeType)messageModeType
                           pinId:(nullable NSString *)pinId
                   quotedMessage:(nullable TSQuotedMessage *)quotedMessage
                     reactionMap:(nullable NSDictionary<NSString *,NSArray<DTReactionSource *> *> *)reactionMap
                 reactionMessage:(nullable DTReactionMessage *)reactionMessage
                          recall:(nullable DTRecallMessage *)recall
    storedShouldStartExpireTimer:(BOOL)storedShouldStartExpireTimer
                translateMessage:(nullable DTTranslateMessage *)translateMessage
              whisperMessageType:(TSWhisperMessageType)whisperMessageType
                        authorId:(NSString *)authorId
         customAttributedMessage:(nullable NSAttributedString *)customAttributedMessage
                   customMessage:(nullable NSString *)customMessage
                      inviteCode:(NSString *)inviteCode
                meetingDetailUrl:(nullable NSString *)meetingDetailUrl
                     meetingName:(nullable NSString *)meetingName
             meetingReminderType:(DTMeetingReminderType)meetingReminderType
                     messageType:(TSInfoMessageType)messageType
                            read:(BOOL)read
                      realSource:(nullable DTRealSourceEntity *)realSource
                   recallPreview:(NSString *)recallPreview
       shouldAffectThreadSorting:(BOOL)shouldAffectThreadSorting
                  sourceDeviceId:(unsigned int)sourceDeviceId
         unregisteredRecipientId:(nullable NSString *)unregisteredRecipientId
    configurationDurationSeconds:(unsigned int)configurationDurationSeconds
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:associatedUniqueThreadId:notifySequenceId:receivedAtTimestamp:sequenceId:serverTimestamp:timestamp:uniqueThreadId:atPersons:attachmentIds:body:card:cardUniqueId:cardVersion:combinedForwardingMessage:contactShare:editable:envelopSource:expireStartedAt:expiresAt:expiresInSeconds:isPinnedMessage:mentions:messageModeType:pinId:quotedMessage:reactionMap:reactionMessage:recall:storedShouldStartExpireTimer:translateMessage:whisperMessageType:authorId:customAttributedMessage:customMessage:inviteCode:meetingDetailUrl:meetingName:meetingReminderType:messageType:read:realSource:recallPreview:shouldAffectThreadSorting:sourceDeviceId:unregisteredRecipientId:configurationDurationSeconds:));

// clang-format on

// --- CODE GENERATION MARKER

/**
 * @param remoteName is nil when created by the local user
 */
- (instancetype)initWithTimestamp:(uint64_t)timestamp
                           thread:(TSThread *)thread
                    messageExpiry:(uint32_t)messageExpiry
              createdByRemoteName:(nullable NSString *)remoteName
           createdInExistingGroup:(BOOL)createdInExistingGroup;

//⚠️Deprecated
- (instancetype)initWithTimestamp:(uint64_t)timestamp
                           thread:(TSThread *)thread
                    configuration:(OWSDisappearingMessagesConfiguration *)configuration
              createdByRemoteName:(nullable NSString *)remoteName
           createdInExistingGroup:(BOOL)createdInExistingGroup;

@end

NS_ASSUME_NONNULL_END
