//
//  OWSRecall.h
//  TTServiceKit
//
//  Created by Kris.s on 2022/10/21.
//

#import <TTServiceKit/TTServiceKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface OWSRecall : BaseModel

@property (nonatomic, assign, readonly) uint64_t originalTimestamp;
@property (nonatomic, assign, readonly) uint32_t originalSourceDevice;
@property (nonatomic, copy, readonly) NSString *originalSource;

@property (nonatomic, assign, readonly) uint64_t timestamp;
@property (nonatomic, assign, readonly) uint32_t sourceDevice;
@property (nonatomic, copy, readonly) NSString *source;
@property (nonatomic, assign, readonly) BOOL editable;

@property (nonatomic, assign) BOOL clearFlag;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                       clearFlag:(BOOL)clearFlag
                        editable:(BOOL)editable
                  originalSource:(NSString *)originalSource
            originalSourceDevice:(unsigned int)originalSourceDevice
               originalTimestamp:(uint64_t)originalTimestamp
                          source:(NSString *)source
                    sourceDevice:(unsigned int)sourceDevice
                       timestamp:(uint64_t)timestamp
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:clearFlag:editable:originalSource:originalSourceDevice:originalTimestamp:source:sourceDevice:timestamp:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                     sourceDevice:(uint32_t)sourceDevice
                           source:(NSString *)source
                originalTimestamp:(uint64_t)originalTimestamp
             originalSourceDevice:(uint32_t)originalSourceDevice
                   originalSource:(NSString *)originalSource
                 originalUniqueId:(NSString *)originalUniqueId
                         editable:(BOOL)editable;

@end

NS_ASSUME_NONNULL_END
