//
//  OWSRecall.m
//  TTServiceKit
//
//  Created by Kris.s on 2022/10/21.
//

#import "OWSRecall.h"

@interface OWSRecall ()

@property (nonatomic, assign, readwrite) uint64_t originalTimestamp;
@property (nonatomic, assign, readwrite) uint32_t originalSourceDevice;
@property (nonatomic, copy, readwrite) NSString *originalSource;
@property (nonatomic, assign, readwrite) uint64_t timestamp;
@property (nonatomic, assign, readwrite) uint32_t sourceDevice;
@property (nonatomic, copy, readwrite) NSString *source;
@property (nonatomic, assign, readwrite) BOOL editable;

@end

@implementation OWSRecall

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                       clearFlag:(BOOL)clearFlag
                        editable:(BOOL)editable
                  originalSource:(NSString *)originalSource
            originalSourceDevice:(unsigned int)originalSourceDevice
               originalTimestamp:(uint64_t)originalTimestamp
                          source:(NSString *)source
                    sourceDevice:(unsigned int)sourceDevice
                       timestamp:(uint64_t)timestamp
{
    self = [super initWithGrdbId:grdbId
                        uniqueId:uniqueId];

    if (!self) {
        return self;
    }

    _clearFlag = clearFlag;
    _editable = editable;
    _originalSource = originalSource;
    _originalSourceDevice = originalSourceDevice;
    _originalTimestamp = originalTimestamp;
    _source = source;
    _sourceDevice = sourceDevice;
    _timestamp = timestamp;

    return self;
}

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                     sourceDevice:(uint32_t)sourceDevice
                           source:(NSString *)source
                originalTimestamp:(uint64_t)originalTimestamp
             originalSourceDevice:(uint32_t)originalSourceDevice
                   originalSource:(NSString *)originalSource
                 originalUniqueId:(NSString *)originalUniqueId
                         editable:(BOOL)editable{
    if(self = [super initWithUniqueId:originalUniqueId]){
        self.timestamp = timestamp;
        self.sourceDevice = sourceDevice;
        self.source = source;
        self.originalTimestamp = originalTimestamp;
        self.originalSourceDevice = originalSourceDevice;
        self.originalSource = originalSource;
        self.editable = editable;
    }
    return self;
}

@end
