//
//  Copyright (c) 2022 Open Whisper Systems. All rights reserved.
//

import Foundation
import GRDB
import SignalCoreKit

// NOTE: This file is generated by /Scripts/sds_codegen/sds_generate.py.
// Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// MARK: - Typed Convenience Methods

@objc
public extension TSInfoMessage {
    // NOTE: This method will fail if the object has unexpected type.
    class func anyFetchInfoMessage(
        uniqueId: String,
        transaction: SDSAnyReadTransaction
    ) -> TSInfoMessage? {
        assert(uniqueId.count > 0)

        guard let object = anyFetch(uniqueId: uniqueId,
                                    transaction: transaction) else {
                                        return nil
        }
        guard let instance = object as? TSInfoMessage else {
            owsFailDebug("Object has unexpected type: \(type(of: object))")
            return nil
        }
        return instance
    }

    // NOTE: This method will fail if the object has unexpected type.
    func anyUpdateInfoMessage(transaction: SDSAnyWriteTransaction, block: (TSInfoMessage) -> Void) {
        anyUpdate(transaction: transaction) { (object) in
            guard let instance = object as? TSInfoMessage else {
                owsFailDebug("Object has unexpected type: \(type(of: object))")
                return
            }
            block(instance)
        }
    }
}

// MARK: - SDSSerializer

// The SDSSerializer protocol specifies how to insert and update the
// row that corresponds to this model.
class TSInfoMessageSerializer: SDSSerializer {

    private let model: TSInfoMessage
    public required init(model: TSInfoMessage) {
        self.model = model
    }

    // MARK: - Record

    func asRecord() throws -> SDSRecord {
        let id: Int64? = model.grdbId?.int64Value

        let recordType: SDSRecordType = .infoMessage
        let uniqueId: String = model.uniqueId

        // Properties
        let associatedUniqueThreadId: String = model.associatedUniqueThreadId
        let atPersons: String? = model.atPersons
        let attachmentIds: Data? = optionalArchive(model.attachmentIds)
        let authorId: String? = model.authorId
        let body: String? = model.body
        let card: Data? = optionalArchive(model.card)
        let combinedForwardingMessage: Data? = optionalArchive(model.combinedForwardingMessage)
        let contactShare: Data? = optionalArchive(model.contactShare)
        let customAttributedMessage: Data? = optionalArchive(model.customAttributedMessage)
        let customMessage: String? = model.customMessage
        let editable: Bool? = model.editable
        let errorType: TSErrorMessageType? = nil
        let expireStartedAt: UInt64? = model.expireStartedAt
        let expiresAt: UInt64? = model.expiresAt
        let expiresInSeconds: UInt32? = model.expiresInSeconds
        let groupChatMode: TSGroupChatMode? = nil
        let groupMetaMessage: TSGroupMetaMessage? = nil
        let hasSyncedTranscript: Bool? = nil
        let inviteCode: String? = model.inviteCode
        let isFromLinkedDevice: Bool? = nil
        let isPinnedMessage: Bool? = model.isPinnedMessage
        let isVoiceMessage: Bool? = nil
        let meetingDetailUrl: String? = model.meetingDetailUrl
        let meetingName: String? = model.meetingName
        let meetingReminderType: DTMeetingReminderType? = model.meetingReminderType
        let messageType: TSInfoMessageType? = model.messageType
        let mostRecentFailureText: String? = nil
        let notifySequenceId: UInt64 = model.notifySequenceId
        let pinId: String? = model.pinId
        let quotedMessage: Data? = optionalArchive(model.quotedMessage)
        let rapidFiles: Data? = nil
        let reactionMap: Data? = optionalArchive(model.reactionMap)
        let reactionMessage: Data? = optionalArchive(model.reactionMessage)
        let read: Bool? = model.wasRead
        let realSource: Data? = optionalArchive(model.realSource)
        let recall: Data? = optionalArchive(model.recall)
        let recallPreview: String? = model.recallPreview
        let receivedAtTimestamp: UInt64 = model.receivedAtTimestamp
        let recipientId: String? = nil
        let recipientStateMap: Data? = nil
        let sequenceId: UInt64 = model.sequenceId
        let serverTimestamp: UInt64 = model.serverTimestamp
        let sourceDeviceId: UInt32? = model.sourceDeviceId
        let timestamp: UInt64 = model.timestamp
        let translateMessage: Data? = optionalArchive(model.translateMessage)
        let threadUniqueId: String = model.uniqueThreadId
        let unregisteredRecipientId: String? = model.unregisteredRecipientId
        let whisperMessageType: TSWhisperMessageType? = model.whisperMessageType
        let storedShouldStartExpireTimer: Bool? = model.storedShouldStartExpireTimer
        let mentionedMsgType: OWSMentionedMsgType? = nil
        let configurationDurationSeconds: UInt32? = nil
        let shouldAffectThreadSorting: Bool? = model.isShouldAffectThreadSorting
        let mentions: Data? = optionalArchive(model.mentions)
        let storedMessageState: TSOutgoingMessageState? = nil
        let envelopSource: String? = model.envelopSource
        let cardUniqueId: String? = model.cardUniqueId
        let cardVersion: UInt32? = model.cardVersion
        let messageModeType: TSMessageModeType? = model.messageModeType

        return InteractionRecord(delegate: model, id: id, recordType: recordType, uniqueId: uniqueId, associatedUniqueThreadId: associatedUniqueThreadId, atPersons: atPersons, attachmentIds: attachmentIds, authorId: authorId, body: body, card: card, combinedForwardingMessage: combinedForwardingMessage, contactShare: contactShare, customAttributedMessage: customAttributedMessage, customMessage: customMessage, editable: editable, errorType: errorType, expireStartedAt: expireStartedAt, expiresAt: expiresAt, expiresInSeconds: expiresInSeconds, groupChatMode: groupChatMode, groupMetaMessage: groupMetaMessage, hasSyncedTranscript: hasSyncedTranscript, inviteCode: inviteCode, isFromLinkedDevice: isFromLinkedDevice, isPinnedMessage: isPinnedMessage, isVoiceMessage: isVoiceMessage, meetingDetailUrl: meetingDetailUrl, meetingName: meetingName, meetingReminderType: meetingReminderType, messageType: messageType, mostRecentFailureText: mostRecentFailureText, notifySequenceId: notifySequenceId, pinId: pinId, quotedMessage: quotedMessage, rapidFiles: rapidFiles, reactionMap: reactionMap, reactionMessage: reactionMessage, read: read, realSource: realSource, recall: recall, recallPreview: recallPreview, receivedAtTimestamp: receivedAtTimestamp, recipientId: recipientId, recipientStateMap: recipientStateMap, sequenceId: sequenceId, serverTimestamp: serverTimestamp, sourceDeviceId: sourceDeviceId, timestamp: timestamp, translateMessage: translateMessage, threadUniqueId: threadUniqueId, unregisteredRecipientId: unregisteredRecipientId, whisperMessageType: whisperMessageType, storedShouldStartExpireTimer: storedShouldStartExpireTimer, mentionedMsgType: mentionedMsgType, configurationDurationSeconds: configurationDurationSeconds, shouldAffectThreadSorting: shouldAffectThreadSorting, mentions: mentions, storedMessageState: storedMessageState, envelopSource: envelopSource, cardUniqueId: cardUniqueId, cardVersion: cardVersion, messageModeType: messageModeType)
    }
}
                                
