//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "OWSReadTracking.h"
#import "DTGroupNotifyEntity.h"
#import "TSMessage.h"

NS_ASSUME_NONNULL_BEGIN

@class SDSAnyReadTransaction;
@class DTRealSourceEntity;

@interface TSInfoMessage : TSMessage <OWSReadTracking>
///TSInfoMessageType 类型只能追加，不能中间插入否则老版本不兼容
typedef NS_ENUM(NSInteger, TSInfoMessageType) {
    TSInfoMessageTypeSessionDidEnd = 0,
    TSInfoMessageUserNotRegistered,
    // TSInfoMessageTypeUnsupportedMessage appears to be obsolete.
    TSInfoMessageTypeUnsupportedMessage,
    TSInfoMessageTypeGroupUpdate,
    TSInfoMessageTypeGroupQuit,
    TSInfoMessageTypeDisappearingMessagesUpdate = 5,
    TSInfoMessageAddToContactsOffer,
    TSInfoMessageVerificationStateChange,
    TSInfoMessageAddUserToProfileWhitelistOffer,
    TSInfoMessageAddGroupToProfileWhitelistOffer,
    TSInfoMessageUserPermissionForbidden,//用户权限被禁止
    TSInfoMessageRecallMessage,
    TSInfoMessagePinMessage,
    TSInfoMessageCallEnd,
    TSInfoMessageGroupReminder,
    TSInfoMessageMeetingReminder,
    TSInfoMessageGroupRemoveMember,
    TSInfoMessageGroupPublishRuleChange,
    TSInfoMessageGroupMemberChangeMeetingAlert,
    TSInfoMessageGroupAddMember,
    TSInfoMessageCoWorkerApproved,
    TSInfoMessageAddToContactsSucess,
    TSInfoMessageNotFriend,
    TSInfoMessageAskFriend,
    TSInfoMessageScreenshotMessage,
    TSInfoMessageUserUnLogined,
    TSInfoMessageUserAccountCanceled,
    TSInfoMessageReportedMessage,
    TSInfoMessageResetIdentityKey,
    TSInfoMessageArchiveMessage
};

//GRDB-Kris--
typedef NSString *InfoMessageUserInfoKey NS_STRING_ENUM;

extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyUpdateMessages;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyOldGroupModel;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyNewGroupModel;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyOldDisappearingMessageToken;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyNewDisappearingMessageToken;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyGroupUpdateSourceAddress;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyProfileChanges;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyChangePhoneNumberUuid;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyChangePhoneNumberOld;
extern InfoMessageUserInfoKey const InfoMessageUserInfoKeyChangePhoneNumberNew;
//--

+ (instancetype)userNotRegisteredMessageInThread:(TSThread *)thread recipientId:(NSString *)recipientId;

+ (instancetype)userPermissionWasForbiddenedMessageInThread:(TSThread *)thread recipientId:(NSString *)recipientId;

@property (atomic, readonly) TSInfoMessageType messageType;
@property (atomic, readonly, nullable) NSString *customMessage;
@property (atomic, nullable) NSAttributedString *customAttributedMessage;
@property (atomic, copy) NSString *recallPreview;
@property (atomic, readonly, nullable) NSString *unregisteredRecipientId;

/// 用于系统消息跳原始消息
@property (nonatomic, nullable) DTRealSourceEntity *realSource;

/// 标记消息来源 如recall
@property (nonatomic, assign) UInt32 sourceDeviceId;
@property (nonatomic, copy) NSString *authorId;

// meeting
@property (nonatomic, readonly) DTMeetingReminderType meetingReminderType;
@property (nonatomic, readonly, nullable) NSString *meetingName;
@property (nonatomic, readonly, nullable) NSString *meetingDetailUrl;
//@property (nonatomic, readonly, nullable) NSString *meetingId;

/// 该条消息是否影响会话排序
@property (nonatomic, assign, getter=isShouldAffectThreadSorting) BOOL shouldAffectThreadSorting;

- (instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
        associatedUniqueThreadId:(NSString *)associatedUniqueThreadId
                notifySequenceId:(uint64_t)notifySequenceId
             receivedAtTimestamp:(uint64_t)receivedAtTimestamp
                      sequenceId:(uint64_t)sequenceId
                 serverTimestamp:(uint64_t)serverTimestamp
                       timestamp:(uint64_t)timestamp
                  uniqueThreadId:(NSString *)uniqueThreadId
                       atPersons:(nullable NSString *)atPersons
                   attachmentIds:(NSArray<NSString *> *)attachmentIds
                            body:(nullable NSString *)body
                            card:(nullable DTCardMessageEntity *)card
                    cardUniqueId:(nullable NSString *)cardUniqueId
                     cardVersion:(unsigned int)cardVersion
       combinedForwardingMessage:(nullable DTCombinedForwardingMessage *)combinedForwardingMessage
                    contactShare:(nullable OWSContact *)contactShare
                        editable:(BOOL)editable
                   envelopSource:(nullable NSString *)envelopSource
                 expireStartedAt:(uint64_t)expireStartedAt
                       expiresAt:(uint64_t)expiresAt
                expiresInSeconds:(unsigned int)expiresInSeconds
                 isPinnedMessage:(BOOL)isPinnedMessage
                        mentions:(nullable NSArray<DTMention *> *)mentions
                 messageModeType:(TSMessageModeType)messageModeType
                           pinId:(nullable NSString *)pinId
                   quotedMessage:(nullable TSQuotedMessage *)quotedMessage
                     reactionMap:(nullable NSDictionary<NSString *,NSArray<DTReactionSource *> *> *)reactionMap
                 reactionMessage:(nullable DTReactionMessage *)reactionMessage
                          recall:(nullable DTRecallMessage *)recall
    storedShouldStartExpireTimer:(BOOL)storedShouldStartExpireTimer
                translateMessage:(nullable DTTranslateMessage *)translateMessage
              whisperMessageType:(TSWhisperMessageType)whisperMessageType
                        authorId:(NSString *)authorId
         customAttributedMessage:(nullable NSAttributedString *)customAttributedMessage
                   customMessage:(nullable NSString *)customMessage
                      inviteCode:(NSString *)inviteCode
                meetingDetailUrl:(nullable NSString *)meetingDetailUrl
                     meetingName:(nullable NSString *)meetingName
             meetingReminderType:(DTMeetingReminderType)meetingReminderType
                     messageType:(TSInfoMessageType)messageType
                            read:(BOOL)read
                      realSource:(nullable DTRealSourceEntity *)realSource
                   recallPreview:(NSString *)recallPreview
       shouldAffectThreadSorting:(BOOL)shouldAffectThreadSorting
                  sourceDeviceId:(unsigned int)sourceDeviceId
         unregisteredRecipientId:(nullable NSString *)unregisteredRecipientId
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:associatedUniqueThreadId:notifySequenceId:receivedAtTimestamp:sequenceId:serverTimestamp:timestamp:uniqueThreadId:atPersons:attachmentIds:body:card:cardUniqueId:cardVersion:combinedForwardingMessage:contactShare:editable:envelopSource:expireStartedAt:expiresAt:expiresInSeconds:isPinnedMessage:mentions:messageModeType:pinId:quotedMessage:reactionMap:reactionMessage:recall:storedShouldStartExpireTimer:translateMessage:whisperMessageType:authorId:customAttributedMessage:customMessage:inviteCode:meetingDetailUrl:meetingName:meetingReminderType:messageType:read:realSource:recallPreview:shouldAffectThreadSorting:sourceDeviceId:unregisteredRecipientId:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                         inThread:(TSThread *)contact
                      messageType:(TSInfoMessageType)messageType;

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                         inThread:(TSThread *)thread
                      messageType:(TSInfoMessageType)messageType
                 expiresInSeconds:(uint32_t)expiresInSeconds
                    customMessage:(NSString * _Nullable)customMessage;

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                         inThread:(TSThread *)thread
                      messageType:(TSInfoMessageType)messageType
                    customMessage:(NSString *)customMessage;

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                         inThread:(TSThread *)thread
                 expiresInSeconds:(uint32_t)expiresInSeconds
                      messageType:(TSInfoMessageType)messageType
                    customMessage:(NSString *)customMessage;

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                  serverTimestamp:(uint64_t)serverTimestamp
                         inThread:(TSThread *)thread
                 expiresInSeconds:(uint32_t)expiresInSeconds
                    customMessage:(NSAttributedString *)customMessage NS_DESIGNATED_INITIALIZER;;

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                  serverTimestamp:(uint64_t)serverTimestamp
                         inThread:(TSThread *)thread
                         authorId:(NSString *)authorId
                         deviceId:(UInt32)deviceId
                 expiresInSeconds:(uint32_t)expiresInSeconds
                    customMessage:(NSAttributedString *)customMessage;

- (instancetype)initWithTimestamp:(uint64_t)timestamp
                         inThread:(TSThread *)thread
                      messageType:(TSInfoMessageType)messageType
          unregisteredRecipientId:(NSString *)unregisteredRecipientId;

- (instancetype)initActionInfoMessageWithType:(TSInfoMessageType)messageType
                                    timestamp:(uint64_t)timestamp
                              serverTimestamp:(uint64_t)serverTimestamp
                                     inThread:(TSThread *)thread
                                customMessage:(NSAttributedString *)customMessage;

- (instancetype)initActionInfoMessageWithType:(TSInfoMessageType)messageType
                                    timestamp:(uint64_t)timestamp
                              serverTimestamp:(uint64_t)serverTimestamp
                                     inThread:(TSThread *)thread
                                customMessage:(NSString *)customMessage
                      customAttributedMessage:(NSAttributedString *)customAttributedMessage;

- (instancetype)initMeetingInfoMessageWithType:(TSInfoMessageType)messageType
                                     timestamp:(uint64_t)timestamp
                               serverTimestamp:(uint64_t)serverTimestamp
                           meetingReminderType:(DTMeetingReminderType)meetingReminderType
                              meetingDetailUrl:(NSString *)meetingDetailUrl
                                   meetingName:(NSString *)meetingName
//                                     meetingId:(NSString *)meetingId
                                      inThread:(TSThread *)thread
                                 customMessage:(NSAttributedString *)customMessage;

- (NSString *)systemMessageTextWithTransaction:(SDSAnyReadTransaction *)transaction;

/// rejoin系统消息可用
@property (nonatomic, copy) NSString *inviteCode;

@end

NS_ASSUME_NONNULL_END
