//
//  Copyright (c) 2018 Open Whisper Systems. All rights reserved.
//

#import "TSInteraction.h"
#import "TSConstants.h"
#import "TSMessageMacro.h"

NS_ASSUME_NONNULL_BEGIN

extern NSString *const MENTIONS_ALL;

/**
 *  Abstract message class.
 */

@class OWSContact;
@class TSAttachment;
@class TSAttachmentStream;
@class TSQuotedMessage;
@class DTCombinedForwardingMessage;
@class DTRecallMessage;
@class DTCardMessageEntity;
@class SDSAnyReadTransaction;
@class SDSAnyWriteTransaction;
@class DTMention;
@class DTTranslateMessage;
@class DTReactionMessage;
@class DTReactionSource;

static NSString *DTEnvelopeSourceRestHotdata = @"restHotdata";

@interface TSMessage : TSInteraction <OWSPreviewText>

// TODO: refactor to readonly
@property (nonatomic, nullable) NSString *envelopSource;
// NOTE: These correspond to just the "body" attachments.
@property (nonatomic) NSArray<NSString *> *attachmentIds;
@property (nonatomic, readonly, nullable) NSString *body;
@property (nonatomic, readonly, nullable) NSString *atPersons;
@property (nonatomic, readonly, nullable) NSArray <DTMention *> *mentions;

// Per-conversation expiration.
@property (nonatomic, readonly) uint32_t expiresInSeconds;
@property (nonatomic, readonly) uint64_t expireStartedAt;
@property (nonatomic, readonly) uint64_t expiresAt;
@property (nonatomic, readonly) BOOL hasPerConversationExpiration;
@property (nonatomic, readonly) BOOL hasPerConversationExpirationStarted;


@property (nonatomic, assign) BOOL editable;
@property (nonatomic, readonly, nullable) TSQuotedMessage *quotedMessage;
@property (nonatomic, readonly, nullable) DTCombinedForwardingMessage *combinedForwardingMessage;
@property (nonatomic, readonly, nullable) OWSContact *contactShare;
@property (nonatomic, strong, nullable) DTTranslateMessage *translateMessage;
@property (nonatomic, strong, nullable) DTRecallMessage *recall;
@property (nonatomic, strong, nullable) DTCardMessageEntity *card;
@property (nonatomic, copy, nullable) NSString *cardUniqueId;
@property (nonatomic, assign) uint32_t cardVersion;

/// 消息是否被pin过
@property (nonatomic, readonly) BOOL isPinned;
@property (nonatomic, copy, nullable) NSString *pinId;
/// DTPinnedMessage 消息
@property (nonatomic, assign) BOOL isPinnedMessage;

@property (nonatomic, strong, nullable) DTReactionMessage *reactionMessage;
@property (nonatomic, assign, readonly) BOOL isReactionMessage;
@property (nonatomic, strong, nullable) NSDictionary <NSString *, NSArray <DTReactionSource*> *> *reactionMap;

@property (nonatomic, assign) TSWhisperMessageType whisperMessageType;

@property (nonatomic, assign) TSMessageModeType messageModeType;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`. Please contact Kris for support.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
        associatedUniqueThreadId:(NSString *)associatedUniqueThreadId
                notifySequenceId:(uint64_t)notifySequenceId
             receivedAtTimestamp:(uint64_t)receivedAtTimestamp
                      sequenceId:(uint64_t)sequenceId
                 serverTimestamp:(uint64_t)serverTimestamp
                       timestamp:(uint64_t)timestamp
                  uniqueThreadId:(NSString *)uniqueThreadId
                       atPersons:(nullable NSString *)atPersons
                   attachmentIds:(NSArray<NSString *> *)attachmentIds
                            body:(nullable NSString *)body
                            card:(nullable DTCardMessageEntity *)card
                    cardUniqueId:(nullable NSString *)cardUniqueId
                     cardVersion:(unsigned int)cardVersion
       combinedForwardingMessage:(nullable DTCombinedForwardingMessage *)combinedForwardingMessage
                    contactShare:(nullable OWSContact *)contactShare
                        editable:(BOOL)editable
                   envelopSource:(nullable NSString *)envelopSource
                 expireStartedAt:(uint64_t)expireStartedAt
                       expiresAt:(uint64_t)expiresAt
                expiresInSeconds:(unsigned int)expiresInSeconds
                 isPinnedMessage:(BOOL)isPinnedMessage
                        mentions:(nullable NSArray<DTMention *> *)mentions
                 messageModeType:(TSMessageModeType)messageModeType
                           pinId:(nullable NSString *)pinId
                   quotedMessage:(nullable TSQuotedMessage *)quotedMessage
                     reactionMap:(nullable NSDictionary<NSString *,NSArray<DTReactionSource *> *> *)reactionMap
                 reactionMessage:(nullable DTReactionMessage *)reactionMessage
                          recall:(nullable DTRecallMessage *)recall
    storedShouldStartExpireTimer:(BOOL)storedShouldStartExpireTimer
                translateMessage:(nullable DTTranslateMessage *)translateMessage
              whisperMessageType:(TSWhisperMessageType)whisperMessageType
NS_DESIGNATED_INITIALIZER NS_SWIFT_NAME(init(grdbId:uniqueId:associatedUniqueThreadId:notifySequenceId:receivedAtTimestamp:sequenceId:serverTimestamp:timestamp:uniqueThreadId:atPersons:attachmentIds:body:card:cardUniqueId:cardVersion:combinedForwardingMessage:contactShare:editable:envelopSource:expireStartedAt:expiresAt:expiresInSeconds:isPinnedMessage:mentions:messageModeType:pinId:quotedMessage:reactionMap:reactionMessage:recall:storedShouldStartExpireTimer:translateMessage:whisperMessageType:));

// clang-format on

// --- CODE GENERATION MARKER

- (instancetype)initInteractionWithTimestamp:(uint64_t)timestamp inThread:(TSThread *)thread authorId:(NSString *)authorId deviceId:(uint32_t)deviceId NS_UNAVAILABLE;

- (instancetype)initMessageWithTimestamp:(uint64_t)timestamp
                         serverTimestamp:(uint64_t)serverTimestamp
                              sequenceId:(uint64_t)sequenceId
                        notifySequenceId:(uint64_t)notifySequenceId
                                inThread:(nullable TSThread *)thread
                                authorId:(nullable NSString *)authorId
                                deviceId:(uint32_t)deviceId
                             messageBody:(nullable NSString *)body
                               atPersons:(nullable NSString *)atPersons
                                mentions:(nullable NSArray <DTMention *> *)mentions
                           attachmentIds:(NSArray<NSString *> *)attachmentIds
                        expiresInSeconds:(uint32_t)expiresInSeconds
                         expireStartedAt:(uint64_t)expireStartedAt
                           quotedMessage:(nullable TSQuotedMessage *)quotedMessage
                       forwardingMessage:(nullable DTCombinedForwardingMessage *)forwardingMessage
                            contactShare:(nullable OWSContact *)contactShare NS_DESIGNATED_INITIALIZER;

- (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;

- (BOOL)hasAttachments;
- (nullable TSAttachment *)attachmentWithTransaction:(SDSAnyReadTransaction *)transaction;

- (void)setQuotedMessageThumbnailAttachmentStream:(TSAttachmentStream *)attachmentStream;

- (BOOL)shouldStartExpireTimer;

#pragma mark - Update With... Methods

- (void)updateWithExpireStartedAt:(uint64_t)expireStartedAt transaction:(SDSAnyWriteTransaction *)transaction;

- (BOOL)isTextMessage;
// 是否是联系人分享
- (BOOL)isContactShareMessage;
// 是否是单条转发
- (BOOL)isSingleForward;
// 是否是转发给多人
- (BOOL)isMultiForward;
//是否是撤回消息
- (BOOL)isRecalMessage;

- (BOOL)isCardMessage;

- (BOOL)isConfidentialMessage;

- (OWSDetailMessageType)detailMessageType;

- (void)updateCardWithCard:(DTCardMessageEntity *)newCard;

@end

NS_ASSUME_NONNULL_END
